import {
  Product,
  PhysicalInventoryItem,
  Customer,
  Booking,
  AlterationTask,
  ReturnRecord,
  SalesOrder,
  PaymentRecord,
  Expense,
  Supplier,
  StaffMember,
  StoreSettings,
  AuditLog,
  Category,
} from '../../src/types/index.js';

export class Store {
  categories: Category[] = [
    {
      id: 'cat-men-sherwani',
      name: 'Sherwani',
      gender: 'men',
      subcategories: ['Royal Velvet', 'Silk Embroidered', 'Achkan', 'Jodhpuri Sherwani', 'Groom Specials'],
    },
    {
      id: 'cat-men-indowestern',
      name: 'Indo-Western',
      gender: 'men',
      subcategories: ['Asymmetrical Kurta', 'Cowl Kurta Set', 'Dhoti Kurta', 'Jacket Sets'],
    },
    {
      id: 'cat-men-bandhgala',
      name: 'Bandhgala & Jodhpuri',
      gender: 'men',
      subcategories: ['Bandhgala Suits', 'Tuxedos', 'Velvet Blazers', 'Prince Coats'],
    },
    {
      id: 'cat-men-kurtajacket',
      name: 'Kurta Jacket & Haldi Set',
      gender: 'men',
      subcategories: ['Mirror Work Kurta', 'Nehru Jacket Set', 'Chanderi Kurta', 'Pathani Suit'],
    },
    {
      id: 'cat-women-lehenga',
      name: 'Bridal & Designer Lehenga',
      gender: 'women',
      subcategories: ['Zardozi Bridal', 'Pastel Heritage', 'Velvet Heavy Lehenga', 'Mirror Work Sangeet', 'Gota Patti'],
    },
    {
      id: 'cat-women-saree',
      name: 'Designer Saree & Gown',
      gender: 'women',
      subcategories: ['Banarasi Silk', 'Kanjivaram', 'Ready-to-wear Saree', 'Indo-Western Gown', 'Cocktail Gowns'],
    },
    {
      id: 'cat-women-sharara',
      name: 'Sharara & Anarkali',
      gender: 'women',
      subcategories: ['Gharara Sets', 'Floor-length Anarkali', 'Peplum Sharara', 'Haldi Specials'],
    },
    {
      id: 'cat-accessories',
      name: 'Wedding Accessories',
      gender: 'accessories',
      subcategories: ['Safa & Pagdi', 'Kalgi & Brooch', 'Pearl Haar', 'Mojari', 'Stole / Dupatta', 'Potli & Clutches'],
    },
  ];

  products: Product[] = [
    {
      id: 'prod-001',
      sku: 'SH-ROYAL-001',
      name: 'Imperial Crimson & Gold Zardozi Sherwani',
      category: 'Sherwani',
      subcategory: 'Royal Velvet',
      gender: 'men',
      brand: 'Sabyasachi Heritage Line',
      designer: 'Tarun Tahiliani Atelier',
      color: 'Crimson Gold',
      fabric: 'Pure Raw Silk with Micro-Velvet Collar',
      sizes: ['38', '40', '42', '44'],
      style: 'Royal Maharaja Cut',
      description: 'Exquisite handcrafted zardozi sherwani with antique gold bullion wire embroidery, accompanied by pearl-embellished buttons and coordinating silk stole.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 45000,
      sellingPrice: 85000,
      rentalPrice: 6500,
      securityDeposit: 10000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Section A - Groom Showcase Racks',
      supplierId: 'sup-001',
      createdDate: '2026-01-10',
      featured: true,
      tags: ['Groom', 'Wedding', 'Zardozi', 'Premium'],
    },
    {
      id: 'prod-002',
      sku: 'LH-BRIDAL-002',
      name: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
      category: 'Bridal & Designer Lehenga',
      subcategory: 'Zardozi Bridal',
      gender: 'women',
      brand: 'Manish Malhotra Couture',
      designer: 'Heritage Crafts Jaipur',
      color: 'Deep Ruby Red',
      fabric: 'Silk Velvet & Banarasi Brocade',
      sizes: ['S', 'M', 'L', 'XL'],
      style: 'Kalidar Flared with 5-Layer Cancan',
      description: 'Heavy 16-kali kalidar lehenga featuring intricate dabka, sequin, and real tilla thread embroidery. Includes dual dupatta styling (heavy velvet & sheer organza veil).',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 68000,
      sellingPrice: 125000,
      rentalPrice: 9500,
      securityDeposit: 15000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Bridal Vault Showcase 01',
      supplierId: 'sup-002',
      createdDate: '2026-01-12',
      featured: true,
      tags: ['Bridal', 'Velvet', 'Heavy Cancan', 'Wedding'],
    },
    {
      id: 'prod-003',
      sku: 'IW-PEACH-003',
      name: 'Pastel Blush Peach Asymmetric Indo-Western Set',
      category: 'Indo-Western',
      subcategory: 'Asymmetrical Kurta',
      gender: 'men',
      brand: 'Torani Couture',
      designer: 'Kunal Rawal Signature',
      color: 'Blush Peach / Rose Gold',
      fabric: 'Tussar Silk with Resham Embroidery',
      sizes: ['38', '40', '42'],
      style: 'Modern Overlap with Pleated Cowl Pant',
      description: 'Contemporary cocktail and sangeet outfit featuring laser-cut geometric resham threadwork, structured shoulder pads, and cowl drape trousers.',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 28000,
      sellingPrice: 48000,
      rentalPrice: 4200,
      securityDeposit: 6000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Section B - Sangeet & Cocktail',
      supplierId: 'sup-001',
      createdDate: '2026-01-15',
      featured: true,
      tags: ['Sangeet', 'Cocktail', 'Pastel', 'Modern'],
    },
    {
      id: 'prod-004',
      sku: 'LH-PASTEL-004',
      name: 'Firozi & Mint Green Floral Chikankari Lehenga',
      category: 'Bridal & Designer Lehenga',
      subcategory: 'Pastel Heritage',
      gender: 'women',
      brand: 'Anushree Reddy Atelier',
      designer: 'Lucknowi Zari Ghar',
      color: 'Mint Green / Ice Blue',
      fabric: 'Georgette with Mukaish & Badla Work',
      sizes: ['XS', 'S', 'M', 'L'],
      style: 'Romantic Pastel Flow',
      description: 'Dreamy daydream lehenga for Haldi, Mehndi, or destination weddings. Embedded with Swarovski crystals and delicate Lucknowi shadow work.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 42000,
      sellingPrice: 75000,
      rentalPrice: 5800,
      securityDeposit: 8000,
      type: 'both',
      condition: 'Excellent',
      location: 'Bridal Section 04',
      supplierId: 'sup-002',
      createdDate: '2026-01-20',
      featured: true,
      tags: ['Mehndi', 'Destination Wedding', 'Pastel'],
    },
    {
      id: 'prod-005',
      sku: 'KJ-HALDI-005',
      name: 'Marigold Mustard Mirror-Work Kurta & Silk Jacket',
      category: 'Kurta Jacket & Haldi Set',
      subcategory: 'Mirror Work Kurta',
      gender: 'men',
      brand: 'Vastra Heritage',
      designer: 'Jaipur Shahi Tailors',
      color: 'Mustard Yellow',
      fabric: 'Chanderi Silk with Real Mirror Embellishments',
      sizes: ['38', '40', '42', '44', '46'],
      style: 'Traditional Gujarati Haldi Outfit',
      description: 'Vibrant Haldi celebration outfit with hand-appliqued mirror work vest, flared kurta, and churidar pajama in breathable silk blend.',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 16000,
      sellingPrice: 28000,
      rentalPrice: 2500,
      securityDeposit: 4000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section C - Haldi Racks',
      supplierId: 'sup-003',
      createdDate: '2026-02-01',
      featured: false,
      tags: ['Haldi', 'Mirror Work', 'Yellow'],
    },
    {
      id: 'prod-006',
      sku: 'BG-MIDNIGHT-006',
      name: 'Midnight Blue Italian Silk Jodhpuri Bandhgala',
      category: 'Bandhgala & Jodhpuri',
      subcategory: 'Bandhgala Suits',
      gender: 'men',
      brand: 'Raymond Royal Luxury',
      designer: 'Jodhpur Heritage Craft',
      color: 'Midnight Navy Blue',
      fabric: 'Italian Super 120s Wool & Mulberry Silk',
      sizes: ['38', '40', '42', '44'],
      style: 'Regal Formal Bandhgala',
      description: 'Structured royal tailored Bandhgala with handcrafted lion crest brass buttons, welt pockets, and matching slim-fit charcoal trousers.',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 32000,
      sellingPrice: 58000,
      rentalPrice: 4800,
      securityDeposit: 7000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section A - Suits Gallery',
      supplierId: 'sup-001',
      createdDate: '2026-02-05',
      featured: false,
      tags: ['Reception', 'Formal', 'Bandhgala'],
    },
    {
      id: 'prod-007',
      sku: 'ACC-GROOM-007',
      name: 'Royal Maharaja Groom Accessories Hamper',
      category: 'Wedding Accessories',
      subcategory: 'Safa & Pagdi',
      gender: 'accessories',
      brand: 'Shahi Shringaar',
      designer: 'Jaipur Gems House',
      color: 'Beige & Maroon Velvet',
      fabric: 'Brocade Silk & Velvet',
      sizes: ['Standard'],
      style: 'Maharaja Accessories Set',
      description: 'Complete groom set containing pre-tied Marwari Safa with antique Kundan Kalgi, pearl layered Mala, brass vintage sword brooch, and zardozi embroidered Mojaris (size 8/9/10).',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 12000,
      sellingPrice: 22000,
      rentalPrice: 1800,
      securityDeposit: 3000,
      type: 'both',
      condition: 'Good',
      location: 'Accessories Glass Cabinet 02',
      supplierId: 'sup-003',
      createdDate: '2026-02-08',
      featured: false,
      tags: ['Safa', 'Kalgi', 'Mojari', 'Groom Accessories'],
    },
  ];

  inventoryItems: PhysicalInventoryItem[] = [
    // Product 1 physical items (Imperial Crimson Sherwani)
    {
      id: 'SH001',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-38',
      barcode: '890123400101',
      size: '38',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-1',
      rentalCount: 11,
      lastRentalDate: '2026-07-28',
      lastCleaningDate: '2026-08-01',
      totalRevenue: 71500,
      cleaningCount: 11,
      repairsCount: 1,
      notes: 'Zari wire retightened in March 2026. Immaculate condition.',
    },
    {
      id: 'SH002',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-40',
      barcode: '890123400102',
      size: '40',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Booked',
      currentLocation: 'Rack A-2 (Reserved)',
      rentalCount: 18,
      lastRentalDate: '2026-08-10',
      lastCleaningDate: '2026-08-14',
      nextAvailableDate: '2026-09-02',
      totalRevenue: 117000,
      cleaningCount: 18,
      repairsCount: 2,
      notes: 'Most popular groom sherwani piece.',
    },
    {
      id: 'SH003',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-42',
      barcode: '890123400103',
      size: '42',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-3',
      rentalCount: 14,
      lastRentalDate: '2026-08-05',
      lastCleaningDate: '2026-08-09',
      totalRevenue: 91000,
      cleaningCount: 14,
      repairsCount: 0,
      notes: 'Ready for immediate pickup or trial.',
    },
    {
      id: 'SH004',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-44',
      barcode: '890123400104',
      size: '44',
      color: 'Crimson Gold',
      condition: 'Good',
      status: 'Cleaning',
      currentLocation: 'Dry Cleaner Express Unit',
      rentalCount: 8,
      lastRentalDate: '2026-08-20',
      lastCleaningDate: '2026-08-22',
      nextAvailableDate: '2026-08-28',
      totalRevenue: 52000,
      cleaningCount: 8,
      repairsCount: 1,
      notes: 'Dispatched to Sparkle Drycleaners for steam press.',
    },

    // Product 2 physical items (Ruby Velvet Bridal Lehenga)
    {
      id: 'LH001',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-S',
      barcode: '890123400201',
      size: 'S',
      color: 'Deep Ruby Red',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-1',
      rentalCount: 9,
      lastRentalDate: '2026-08-02',
      lastCleaningDate: '2026-08-06',
      totalRevenue: 85500,
      cleaningCount: 9,
      repairsCount: 1,
      notes: 'Includes padded 34B blouse with drawstring tassels.',
    },
    {
      id: 'LH002',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-M',
      barcode: '890123400202',
      size: 'M',
      color: 'Deep Ruby Red',
      condition: 'Excellent',
      status: 'Rented',
      currentLocation: 'With Customer (Devangi Joshi)',
      rentalCount: 16,
      lastRentalDate: '2026-08-22',
      lastCleaningDate: '2026-08-18',
      nextAvailableDate: '2026-08-30',
      totalRevenue: 152000,
      cleaningCount: 16,
      repairsCount: 3,
      notes: 'Due return on 28 Aug 2026.',
    },
    {
      id: 'LH003',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-L',
      barcode: '890123400203',
      size: 'L',
      color: 'Deep Ruby Red',
      condition: 'Good',
      status: 'Alteration',
      currentLocation: 'Tailor Master Desk - Ramesh Tailor',
      rentalCount: 12,
      lastRentalDate: '2026-08-12',
      lastCleaningDate: '2026-08-16',
      nextAvailableDate: '2026-08-29',
      totalRevenue: 114000,
      cleaningCount: 12,
      repairsCount: 1,
      notes: 'Blouse margin release by 1.5 inches for upcoming wedding booking.',
    },

    // Product 3 physical items (Pastel Indo-Western)
    {
      id: 'IW001',
      productId: 'prod-003',
      sku: 'IW-PEACH-003-40',
      barcode: '890123400301',
      size: '40',
      color: 'Blush Peach',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack B-1',
      rentalCount: 7,
      lastRentalDate: '2026-07-30',
      lastCleaningDate: '2026-08-04',
      totalRevenue: 29400,
      cleaningCount: 7,
      repairsCount: 0,
    },
    {
      id: 'IW002',
      productId: 'prod-003',
      sku: 'IW-PEACH-003-42',
      barcode: '890123400302',
      size: '42',
      color: 'Blush Peach',
      condition: 'Excellent',
      status: 'Booked',
      currentLocation: 'Rack B-2',
      rentalCount: 9,
      lastRentalDate: '2026-08-08',
      lastCleaningDate: '2026-08-12',
      nextAvailableDate: '2026-09-05',
      totalRevenue: 37800,
      cleaningCount: 9,
      repairsCount: 0,
    },

    // Product 4 physical items (Chikankari Pastel Lehenga)
    {
      id: 'LH004',
      productId: 'prod-004',
      sku: 'LH-PASTEL-004-M',
      barcode: '890123400401',
      size: 'M',
      color: 'Mint Green',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-4',
      rentalCount: 6,
      lastRentalDate: '2026-08-01',
      lastCleaningDate: '2026-08-05',
      totalRevenue: 34800,
      cleaningCount: 6,
      repairsCount: 0,
    },

    // Product 5 physical items (Haldi Kurta Jacket)
    {
      id: 'KJ001',
      productId: 'prod-005',
      sku: 'KJ-HALDI-005-40',
      barcode: '890123400501',
      size: '40',
      color: 'Mustard Yellow',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack C-1',
      rentalCount: 15,
      lastRentalDate: '2026-08-15',
      lastCleaningDate: '2026-08-19',
      totalRevenue: 37500,
      cleaningCount: 15,
      repairsCount: 1,
    },
    {
      id: 'KJ002',
      productId: 'prod-005',
      sku: 'KJ-HALDI-005-42',
      barcode: '890123400502',
      size: '42',
      color: 'Mustard Yellow',
      condition: 'Minor Damage',
      status: 'Repair',
      currentLocation: 'Tailoring Section Table 2',
      rentalCount: 12,
      lastRentalDate: '2026-08-18',
      lastCleaningDate: '2026-08-20',
      nextAvailableDate: '2026-08-30',
      totalRevenue: 30000,
      cleaningCount: 12,
      repairsCount: 3,
      notes: '2 small mirrors loose on right chest pocket. Under repair.',
    },

    // Product 6 physical items (Bandhgala)
    {
      id: 'BG001',
      productId: 'prod-006',
      sku: 'BG-MIDNIGHT-006-40',
      barcode: '890123400601',
      size: '40',
      color: 'Midnight Navy Blue',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-5',
      rentalCount: 8,
      lastRentalDate: '2026-08-04',
      lastCleaningDate: '2026-08-08',
      totalRevenue: 38400,
      cleaningCount: 8,
      repairsCount: 0,
    },
    {
      id: 'BG002',
      productId: 'prod-006',
      sku: 'BG-MIDNIGHT-006-42',
      barcode: '890123400602',
      size: '42',
      color: 'Midnight Navy Blue',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-6',
      rentalCount: 10,
      lastRentalDate: '2026-08-02',
      lastCleaningDate: '2026-08-06',
      totalRevenue: 48000,
      cleaningCount: 10,
      repairsCount: 0,
    },

    // Product 7 (Groom Accessories)
    {
      id: 'ACC001',
      productId: 'prod-007',
      sku: 'ACC-GROOM-007-STD',
      barcode: '890123400701',
      size: 'Standard',
      color: 'Beige & Maroon',
      condition: 'Good',
      status: 'Available',
      currentLocation: 'Accessory Showcase 01',
      rentalCount: 14,
      lastRentalDate: '2026-08-11',
      lastCleaningDate: '2026-08-13',
      totalRevenue: 25200,
      cleaningCount: 14,
      repairsCount: 1,
    },
  ];

  customers: Customer[] = [
    {
      id: 'cust-001',
      customerId: 'CUST-2026-001',
      name: 'Vikram & Ananya Rathore',
      phone: '+91 98250 14892',
      whatsapp: '+91 98250 14892',
      email: 'vikram.rathore@gmail.com',
      address: '702, Shivalik Highstreet, Judges Bungalow Road, Bodakdev',
      city: 'Ahmedabad',
      dateOfBirth: '1995-11-14',
      notes: 'VIP Groom customer. Grand wedding at Jagmandir Palace, Udaipur.',
      menMeasurements: {
        height: "5'11\"",
        weight: '76 kg',
        chest: '40.5',
        waist: '33',
        shoulder: '18.5',
        sleeve: '25.5',
        neck: '16',
        kurtaLength: '42',
        sherwaniLength: '43.5',
        pantLength: '41',
        thigh: '23',
        bottom: '14.5',
        shoeSize: '9',
      },
      womenMeasurements: {
        height: "5'6\"",
        bust: '35',
        waist: '28',
        hip: '38',
        shoulder: '15',
        sleeve: '11',
        blouseLength: '14.5',
        lehengaWaist: '29',
        lehengaLength: '42',
        dupattaLength: '2.6m',
        shoeSize: '6',
      },
      totalBookings: 2,
      totalPurchases: 1,
      outstandingAmount: 4500,
      createdDate: '2026-04-10',
    },
    {
      id: 'cust-002',
      customerId: 'CUST-2026-002',
      name: 'Devangi & Hardik Joshi',
      phone: '+91 98791 22340',
      whatsapp: '+91 98791 22340',
      email: 'devangi.joshi@outlook.com',
      address: 'B-404, Orchid Elegance, South Bopal',
      city: 'Ahmedabad',
      dateOfBirth: '1997-03-22',
      notes: 'Bridal customer for 4-day wedding rituals.',
      womenMeasurements: {
        height: "5'4\"",
        bust: '36',
        waist: '30',
        hip: '39',
        shoulder: '14.5',
        sleeve: '10.5',
        blouseLength: '15',
        lehengaWaist: '31',
        lehengaLength: '40.5',
        dupattaLength: '2.5m',
        shoeSize: '7',
      },
      totalBookings: 3,
      totalPurchases: 0,
      outstandingAmount: 0,
      createdDate: '2026-05-18',
    },
    {
      id: 'cust-003',
      customerId: 'CUST-2026-003',
      name: 'Chirag Singhania',
      phone: '+91 99099 88123',
      whatsapp: '+91 99099 88123',
      email: 'chirag.s@singhaniaexports.in',
      address: '22, Gulmohar Park, Satellite',
      city: 'Ahmedabad',
      dateOfBirth: '1992-08-05',
      notes: 'Brother of the bride. Needs multiple event outfits.',
      menMeasurements: {
        height: "6'0\"",
        weight: '82 kg',
        chest: '42',
        waist: '35',
        shoulder: '19',
        sleeve: '26',
        neck: '16.5',
        kurtaLength: '43',
        sherwaniLength: '44',
        pantLength: '42',
        thigh: '24',
        bottom: '15',
        shoeSize: '10',
      },
      totalBookings: 1,
      totalPurchases: 2,
      outstandingAmount: 2000,
      createdDate: '2026-06-02',
    },
  ];

  bookings: Booking[] = [
    {
      id: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      customerPhone: '+91 98250 14892',
      customerWhatsapp: '+91 98250 14892',
      weddingTitle: 'Vikram & Ananya Royal Wedding',
      events: [
        {
          id: 'ev-1',
          name: 'Sangeet',
          eventDate: '2026-08-30',
          eventTime: '07:30 PM',
          venue: 'The Grand Bhagwati, SG Highway',
        },
        {
          id: 'ev-2',
          name: 'Wedding',
          eventDate: '2026-08-31',
          eventTime: '11:00 AM',
          venue: 'Umaid Bhawan Grounds / YMCA Club',
        },
      ],
      items: [
        {
          productId: 'prod-001',
          physicalItemId: 'SH002',
          productName: 'Imperial Crimson & Gold Zardozi Sherwani',
          sku: 'SH-ROYAL-001-40',
          size: '40',
          rentalPrice: 6500,
          securityDeposit: 10000,
          eventName: 'Wedding',
          alterationDetails: 'Sleeve hem length reduced by 0.5 inch.',
        },
        {
          productId: 'prod-003',
          physicalItemId: 'IW002',
          productName: 'Pastel Blush Peach Asymmetric Indo-Western Set',
          sku: 'IW-PEACH-003-42',
          size: '42',
          rentalPrice: 4200,
          securityDeposit: 6000,
          eventName: 'Sangeet',
        },
      ],
      rentalStartDate: '2026-08-29',
      rentalEndDate: '2026-09-02',
      pickupDate: '2026-08-29',
      returnDate: '2026-09-02',
      deliveryAddress: 'Store Pickup Scheduled by Vikram',
      rentalAmount: 10700,
      securityDeposit: 16000,
      discount: 1000,
      taxRate: 5,
      taxAmount: 485,
      totalAmount: 10185, // rental + tax - discount
      advancePaid: 5000,
      remainingAmount: 5185,
      depositCollected: 16000,
      depositHeld: 16000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Ready',
      paymentStatus: 'Partial',
      notes: 'Customer requested matching pagdi on pickup.',
      createdDate: '2026-08-15',
    },
    {
      id: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      customerPhone: '+91 98791 22340',
      customerWhatsapp: '+91 98791 22340',
      weddingTitle: 'Devangi Joshi Destination Wedding',
      events: [
        {
          id: 'ev-3',
          name: 'Wedding',
          eventDate: '2026-08-26',
          venue: 'Kensville Golf & Country Club',
        },
      ],
      items: [
        {
          productId: 'prod-002',
          physicalItemId: 'LH002',
          productName: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
          sku: 'LH-BRIDAL-002-M',
          size: 'M',
          rentalPrice: 9500,
          securityDeposit: 15000,
          eventName: 'Wedding',
        },
      ],
      rentalStartDate: '2026-08-24',
      rentalEndDate: '2026-08-28',
      pickupDate: '2026-08-24',
      returnDate: '2026-08-28',
      rentalAmount: 9500,
      securityDeposit: 15000,
      discount: 500,
      taxRate: 5,
      taxAmount: 450,
      totalAmount: 9450,
      advancePaid: 9450,
      remainingAmount: 0,
      depositCollected: 15000,
      depositHeld: 15000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Active Rental',
      paymentStatus: 'Paid',
      notes: 'Outfit currently in active rental. Scheduled return on 28 Aug.',
      createdDate: '2026-08-10',
    },
  ];

  alterations: AlterationTask[] = [
    {
      id: 'alt-001',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram Rathore',
      customerPhone: '+91 98250 14892',
      productId: 'prod-001',
      productName: 'Imperial Crimson & Gold Zardozi Sherwani',
      physicalItemId: 'SH002',
      size: '40',
      alterationType: 'Sleeve Length Shortening',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      dueDate: '2026-08-28',
      status: 'Ready',
      instructions: 'Reduce right and left sleeves by 0.5 inches without disturbing bullion cuff border.',
      createdDate: '2026-08-16',
      completedDate: '2026-08-25',
    },
    {
      id: 'alt-002',
      bookingId: 'bk-003',
      bookingNumber: 'BK-2026-0803',
      customerId: 'cust-002',
      customerName: 'Devangi Joshi',
      customerPhone: '+91 98791 22340',
      productId: 'prod-002',
      productName: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
      physicalItemId: 'LH003',
      size: 'L',
      alterationType: 'Blouse Margin Open',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      dueDate: '2026-08-29',
      status: 'In Progress',
      instructions: 'Release side seam allowance by 1.2 inches for comfortable chest fit.',
      createdDate: '2026-08-24',
    },
  ];

  returns: ReturnRecord[] = [
    {
      id: 'ret-001',
      bookingId: 'bk-prev-01',
      bookingNumber: 'BK-2026-0790',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      returnDate: '2026-08-20',
      scheduledReturnDate: '2026-08-18',
      isLate: true,
      lateDays: 2,
      lateFeePerDay: 500,
      totalLateFee: 1000,
      inspectedItems: [
        {
          physicalItemId: 'KJ002',
          productId: 'prod-005',
          productName: 'Marigold Mustard Mirror-Work Kurta',
          size: '42',
          condition: 'Minor Damage',
          damageType: 'Loose Mirror Embroidery',
          damageDescription: 'Two small glass mirrors came off at front right panel.',
          damageRepairCost: 350,
          customerDeduction: 350,
          cleaningRequired: true,
          repairRequired: true,
        },
      ],
      totalDamageCost: 350,
      totalCustomerDeduction: 1350, // 1000 late fee + 350 damage
      securityDepositHeld: 4000,
      netDepositRefund: 2650,
      netCustomerPayable: 0,
      processedBy: 'Manojbhai Patel (Store Manager)',
      status: 'Completed',
      notes: 'Customer accepted deduction without dispute. Refund processed via UPI.',
      createdDate: '2026-08-20',
    },
  ];

  salesOrders: SalesOrder[] = [
    {
      id: 'so-001',
      orderNumber: 'SO-2026-0041',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      customerPhone: '+91 99099 88123',
      items: [
        {
          productId: 'prod-007',
          productName: 'Royal Maharaja Groom Accessories Hamper',
          sku: 'ACC-GROOM-007',
          size: 'Standard',
          price: 22000,
          quantity: 1,
          total: 22000,
        },
      ],
      subtotal: 22000,
      discount: 1000,
      taxRate: 5,
      taxAmount: 1050,
      finalTotal: 22050,
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      deliveryStatus: 'Delivered',
      createdDate: '2026-08-18',
      notes: 'Immediate handover at showroom billing counter.',
    },
  ];

  payments: PaymentRecord[] = [
    {
      id: 'pay-001',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      amount: 5000,
      paymentType: 'Advance',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/3891029192/HDFC',
      invoiceNumber: 'INV-2026-0801',
      date: '2026-08-15',
      notes: 'Advance booking token',
      receivedBy: 'Pooja Shah (Cashier)',
    },
    {
      id: 'pay-002',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      amount: 16000,
      paymentType: 'Deposit',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/3891048821/HDFC',
      invoiceNumber: 'DEP-2026-0801',
      date: '2026-08-15',
      notes: 'Full security deposit received into escrow ledger',
      receivedBy: 'Pooja Shah (Cashier)',
    },
    {
      id: 'pay-003',
      bookingId: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      amount: 9450,
      paymentType: 'Final Payment',
      paymentMethod: 'Credit Card',
      transactionReference: 'POS/ICICI/882190',
      invoiceNumber: 'INV-2026-0802',
      date: '2026-08-24',
      notes: 'Full rental cleared before outfit handover',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-004',
      bookingId: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      amount: 15000,
      paymentType: 'Deposit',
      paymentMethod: 'Cash',
      invoiceNumber: 'DEP-2026-0802',
      date: '2026-08-24',
      notes: 'Cash security deposit held in store safe',
      receivedBy: 'Manojbhai Patel',
    },
  ];

  expenses: Expense[] = [
    {
      id: 'exp-001',
      category: 'Cleaning',
      title: 'Monthly Heavy Silk Drycleaning & Ozone Sanitization',
      amount: 12500,
      date: '2026-08-22',
      paidTo: 'Sparkle Luxury Garment Cleaners',
      paymentMethod: 'UPI',
      associatedType: 'Business',
      notes: 'Batch of 18 wedding outfits cleaned and packed with acid-free tissue paper.',
    },
    {
      id: 'exp-002',
      category: 'Tailoring',
      title: 'Master Tailor Fortnightly Piece-Rate Alteration Payout',
      amount: 16800,
      date: '2026-08-20',
      paidTo: 'Ramesh Master & Team',
      paymentMethod: 'Bank Transfer',
      associatedType: 'Business',
      notes: 'Alteration on 24 wedding pieces completed on schedule.',
    },
    {
      id: 'exp-003',
      category: 'Rent',
      title: 'Showroom Lease - Judges Bungalow Road Flagship',
      amount: 85000,
      date: '2026-08-01',
      paidTo: 'Shivalik Properties Ltd',
      paymentMethod: 'Bank Transfer',
      associatedType: 'Business',
    },
    {
      id: 'exp-004',
      category: 'Packaging',
      title: 'Branded Luxury Velvet Garment Bags & Wooden Hangers',
      amount: 9400,
      date: '2026-08-10',
      paidTo: 'Royal Craft Box & Packaging Surat',
      paymentMethod: 'UPI',
      associatedType: 'Business',
    },
  ];

  suppliers: Supplier[] = [
    {
      id: 'sup-001',
      name: 'Royal Heritage Weaves Jaipur',
      contactPerson: 'Harishankar Sharma',
      phone: '+91 94140 33890',
      email: 'orders@royalheritageweaves.in',
      address: 'Johari Bazaar, Near Hawa Mahal',
      city: 'Jaipur',
      categoriesProvided: ['Sherwani', 'Bandhgala', 'Indo-Western'],
      gstNumber: '08AAACR8821N1Z5',
      totalSupplied: 480000,
      pendingBalance: 25000,
      notes: 'Specialist in pure silk bullion and hand zardozi work.',
    },
    {
      id: 'sup-002',
      name: 'Vrindavan Zari & Bridal Emporium',
      contactPerson: 'Sunilbhai Vora',
      phone: '+91 98241 66720',
      email: 'vrindavan.zari@gmail.com',
      address: 'Ring Road Textile Market',
      city: 'Surat',
      categoriesProvided: ['Bridal Lehenga', 'Designer Saree', 'Dupattas'],
      gstNumber: '24AABPV1928K1ZZ',
      totalSupplied: 890000,
      pendingBalance: 40000,
      notes: 'Top tier bridal lehenga fabrics with high cancan support.',
    },
    {
      id: 'sup-003',
      name: 'Shahi Pagdi & Accessories Delhi',
      contactPerson: 'Gurmeet Singh',
      phone: '+91 98110 55432',
      email: 'gurmeet@shahipagdi.com',
      address: 'Chandni Chowk Market',
      city: 'New Delhi',
      categoriesProvided: ['Safa & Pagdi', 'Kalgi & Brooch', 'Mojaris'],
      gstNumber: '07AAACS1120M1ZK',
      totalSupplied: 140000,
      pendingBalance: 0,
      notes: 'Pre-tied luxury safas with velvet trims.',
    },
  ];

  staff: StaffMember[] = [
    {
      id: 'stf-001',
      name: 'Manojbhai Patel',
      role: 'Manager',
      phone: '+91 98251 00223',
      email: 'manoj.patel@vastraveda.in',
      salary: 45000,
      joiningDate: '2024-01-15',
      active: true,
      tasksAssigned: 12,
      specialization: 'Showroom Operations & Return Inspections',
    },
    {
      id: 'stf-002',
      name: 'Pooja Shah',
      role: 'Sales Staff',
      phone: '+91 97230 44512',
      email: 'pooja.shah@vastraveda.in',
      salary: 28000,
      joiningDate: '2024-06-01',
      active: true,
      tasksAssigned: 8,
      specialization: 'Bridal Consultation & Styling',
    },
    {
      id: 'stf-003',
      name: 'Ramesh Darji',
      role: 'Tailor',
      phone: '+91 94280 11928',
      email: 'ramesh.tailor@vastraveda.in',
      salary: 32000,
      joiningDate: '2024-02-10',
      active: true,
      tasksAssigned: 2,
      specialization: 'Master Sherwani & Blouse Master',
    },
    {
      id: 'stf-004',
      name: 'Ketan Vaghela',
      role: 'Inventory Staff',
      phone: '+91 96010 33451',
      email: 'ketan.v@vastraveda.in',
      salary: 22000,
      joiningDate: '2025-01-05',
      active: true,
      tasksAssigned: 6,
      specialization: 'QR Tagging, Dryclean Handover & Quality Inspection',
    },
  ];

  settings: StoreSettings = {
    businessName: 'VastraVeda Bridal & Groom Couture',
    tagline: 'India’s Premier Wedding Wear Rental & Bespoke Studio',
    gstin: '24AAFCV9821L1Z4',
    address: 'Showroom 101-104, Shivalik Highstreet, Judges Bungalow Road, Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    phone: '+91 79 4890 2200',
    whatsapp: '+91 98250 14892',
    email: 'contact@vastravedacouture.com',
    upiId: 'vastraveda@okhdfcbank',
    currencySymbol: '₹',
    defaultTaxRate: 5,
    defaultDepositRate: 50, // 50%
    lateFeePerDay: 500, // ₹500 per day
    cleaningBufferDays: 1, // 1 day dryclean buffer
    alterationBufferDays: 2, // 2 days tailoring buffer
    termsAndConditions:
      '1. Security deposit is fully refundable subject to item condition on return inspection.\n2. Late returns attract ₹500/day per garment.\n3. Any fabric tear, wine/grease stains, or lost brooch accessories will be deducted from the security deposit at actual repair/replacement cost.\n4. Outfits must be returned on the scheduled return date before 8:00 PM.',
    language: 'en',
  };

  auditLogs: AuditLog[] = [
    {
      id: 'log-001',
      timestamp: '2026-08-26 09:30:15',
      user: 'Manojbhai Patel (Manager)',
      action: 'Created Booking',
      target: 'BK-2026-0801',
      details: 'Booked 2 outfits for Vikram & Ananya Rathore wedding.',
    },
    {
      id: 'log-002',
      timestamp: '2026-08-26 10:14:02',
      user: 'Pooja Shah (Sales)',
      action: 'Logged Advance Payment',
      target: 'BK-2026-0801',
      details: 'Recorded ₹5,000 Advance + ₹16,000 Security Deposit via UPI.',
    },
    {
      id: 'log-003',
      timestamp: '2026-08-25 16:45:00',
      user: 'Ramesh Darji (Tailor)',
      action: 'Completed Alteration',
      target: 'SH002 (Sleeve shortening)',
      details: 'Marked alteration task as Ready.',
    },
  ];

  // Helper method: Check date overlap for a physical item
  isItemAvailableForDates(
    physicalItemId: string,
    startDateStr: string,
    endDateStr: string,
    excludeBookingId?: string
  ): { available: boolean; conflictingBooking?: Booking; reason?: string } {
    const item = this.inventoryItems.find((i) => i.id === physicalItemId);
    if (!item) {
      return { available: false, reason: 'Physical item not found' };
    }

    if (item.status === 'Sold' || item.status === 'Lost' || item.status === 'Damaged' || item.status === 'Inactive') {
      return { available: false, reason: `Item is currently marked as ${item.status}` };
    }

    const reqStart = new Date(startDateStr).getTime();
    const reqEnd = new Date(endDateStr).getTime();

    // Check active / confirmed bookings that include this physical item
    for (const booking of this.bookings) {
      if (excludeBookingId && booking.id === excludeBookingId) continue;
      if (booking.bookingStatus === 'Cancelled' || booking.bookingStatus === 'Completed') continue;

      const hasItem = booking.items.some((bi) => bi.physicalItemId === physicalItemId);
      if (!hasItem) continue;

      // Calculate buffer dates (add 1 day for cleaning/alteration buffer)
      const bStart = new Date(booking.rentalStartDate).getTime();
      const bEnd = new Date(booking.rentalEndDate).getTime() + this.settings.cleaningBufferDays * 86400000;

      // Overlap condition: reqStart <= bEnd && reqEnd >= bStart
      if (reqStart <= bEnd && reqEnd >= bStart) {
        return {
          available: false,
          conflictingBooking: booking,
          reason: `Booked for ${booking.customerName} (${booking.rentalStartDate} to ${booking.rentalEndDate})`,
        };
      }
    }

    return { available: true };
  }
}

export const db = new Store();
