import {
  Product,
  PhysicalInventoryItem,
  Customer,
  Booking,
  AlterationTask,
  ReturnRecord,
  SalesOrder,
  PaymentRecord,
  Expense,
  Supplier,
  StaffMember,
  StoreSettings,
  AuditLog,
  Category,
} from '../../src/types/index.js';

export class Store {
  categories: Category[] = [
    {
      id: 'cat-men-sherwani',
      name: 'Sherwani',
      gender: 'men',
      subcategories: ['Royal Velvet', 'Silk Embroidered', 'Achkan', 'Jodhpuri Sherwani', 'Groom Specials'],
    },
    {
      id: 'cat-men-indowestern',
      name: 'Indo-Western',
      gender: 'men',
      subcategories: ['Asymmetrical Kurta', 'Cowl Kurta Set', 'Dhoti Kurta', 'Jacket Sets'],
    },
    {
      id: 'cat-men-bandhgala',
      name: 'Bandhgala & Jodhpuri',
      gender: 'men',
      subcategories: ['Bandhgala Suits', 'Tuxedos', 'Velvet Blazers', 'Prince Coats'],
    },
    {
      id: 'cat-men-kurtajacket',
      name: 'Kurta Jacket & Haldi Set',
      gender: 'men',
      subcategories: ['Mirror Work Kurta', 'Nehru Jacket Set', 'Chanderi Kurta', 'Pathani Suit'],
    },
    {
      id: 'cat-women-lehenga',
      name: 'Bridal & Designer Lehenga',
      gender: 'women',
      subcategories: ['Zardozi Bridal', 'Pastel Heritage', 'Velvet Heavy Lehenga', 'Mirror Work Sangeet', 'Gota Patti'],
    },
    {
      id: 'cat-women-saree',
      name: 'Designer Saree & Gown',
      gender: 'women',
      subcategories: ['Banarasi Silk', 'Kanjivaram', 'Ready-to-wear Saree', 'Indo-Western Gown', 'Cocktail Gowns'],
    },
    {
      id: 'cat-women-sharara',
      name: 'Sharara & Anarkali',
      gender: 'women',
      subcategories: ['Gharara Sets', 'Floor-length Anarkali', 'Peplum Sharara', 'Haldi Specials'],
    },
    {
      id: 'cat-accessories',
      name: 'Wedding Accessories',
      gender: 'accessories',
      subcategories: ['Safa & Pagdi', 'Kalgi & Brooch', 'Pearl Haar', 'Mojari', 'Stole / Dupatta', 'Potli & Clutches'],
    },
  ];

  products: Product[] = [
    {
      id: 'prod-001',
      sku: 'SH-ROYAL-001',
      name: 'Imperial Crimson & Gold Zardozi Sherwani',
      category: 'Sherwani',
      subcategory: 'Royal Velvet',
      gender: 'men',
      brand: 'Sabyasachi Heritage Line',
      designer: 'Tarun Tahiliani Atelier',
      color: 'Crimson Gold',
      fabric: 'Pure Raw Silk with Micro-Velvet Collar',
      sizes: ['38', '40', '42', '44'],
      style: 'Royal Maharaja Cut',
      description: 'Exquisite handcrafted zardozi sherwani with antique gold bullion wire embroidery, accompanied by pearl-embellished buttons and coordinating silk stole.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 45000,
      sellingPrice: 85000,
      rentalPrice: 6500,
      securityDeposit: 10000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Section A - Groom Showcase Racks',
      supplierId: 'sup-001',
      createdDate: '2026-01-10',
      featured: true,
      tags: ['Groom', 'Wedding', 'Zardozi', 'Premium'],
    },
    {
      id: 'prod-002',
      sku: 'LH-BRIDAL-002',
      name: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
      category: 'Bridal & Designer Lehenga',
      subcategory: 'Zardozi Bridal',
      gender: 'women',
      brand: 'Manish Malhotra Couture',
      designer: 'Heritage Crafts Jaipur',
      color: 'Deep Ruby Red',
      fabric: 'Silk Velvet & Banarasi Brocade',
      sizes: ['S', 'M', 'L', 'XL'],
      style: 'Kalidar Flared with 5-Layer Cancan',
      description: 'Heavy 16-kali kalidar lehenga featuring intricate dabka, sequin, and real tilla thread embroidery. Includes dual dupatta styling (heavy velvet & sheer organza veil).',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 68000,
      sellingPrice: 125000,
      rentalPrice: 9500,
      securityDeposit: 15000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Bridal Vault Showcase 01',
      supplierId: 'sup-002',
      createdDate: '2026-01-12',
      featured: true,
      tags: ['Bridal', 'Velvet', 'Heavy Cancan', 'Wedding'],
    },
    {
      id: 'prod-003',
      sku: 'IW-PEACH-003',
      name: 'Pastel Blush Peach Asymmetric Indo-Western Set',
      category: 'Indo-Western',
      subcategory: 'Asymmetrical Kurta',
      gender: 'men',
      brand: 'Torani Couture',
      designer: 'Kunal Rawal Signature',
      color: 'Blush Peach / Rose Gold',
      fabric: 'Tussar Silk with Resham Embroidery',
      sizes: ['38', '40', '42'],
      style: 'Modern Overlap with Pleated Cowl Pant',
      description: 'Contemporary cocktail and sangeet outfit featuring laser-cut geometric resham threadwork, structured shoulder pads, and cowl drape trousers.',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 28000,
      sellingPrice: 48000,
      rentalPrice: 4200,
      securityDeposit: 6000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Section B - Sangeet & Cocktail',
      supplierId: 'sup-001',
      createdDate: '2026-01-15',
      featured: true,
      tags: ['Sangeet', 'Cocktail', 'Pastel', 'Modern'],
    },
    {
      id: 'prod-004',
      sku: 'LH-PASTEL-004',
      name: 'Firozi & Mint Green Floral Chikankari Lehenga',
      category: 'Bridal & Designer Lehenga',
      subcategory: 'Pastel Heritage',
      gender: 'women',
      brand: 'Anushree Reddy Atelier',
      designer: 'Lucknowi Zari Ghar',
      color: 'Mint Green / Ice Blue',
      fabric: 'Georgette with Mukaish & Badla Work',
      sizes: ['XS', 'S', 'M', 'L'],
      style: 'Romantic Pastel Flow',
      description: 'Dreamy daydream lehenga for Haldi, Mehndi, or destination weddings. Embedded with Swarovski crystals and delicate Lucknowi shadow work.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 42000,
      sellingPrice: 75000,
      rentalPrice: 5800,
      securityDeposit: 8000,
      type: 'both',
      condition: 'Excellent',
      location: 'Bridal Section 04',
      supplierId: 'sup-002',
      createdDate: '2026-01-20',
      featured: true,
      tags: ['Mehndi', 'Destination Wedding', 'Pastel'],
    },
    {
      id: 'prod-005',
      sku: 'KJ-HALDI-005',
      name: 'Marigold Mustard Mirror-Work Kurta & Silk Jacket',
      category: 'Kurta Jacket & Haldi Set',
      subcategory: 'Mirror Work Kurta',
      gender: 'men',
      brand: 'Vastra Heritage',
      designer: 'Jaipur Shahi Tailors',
      color: 'Mustard Yellow',
      fabric: 'Chanderi Silk with Real Mirror Embellishments',
      sizes: ['38', '40', '42', '44', '46'],
      style: 'Traditional Gujarati Haldi Outfit',
      description: 'Vibrant Haldi celebration outfit with hand-appliqued mirror work vest, flared kurta, and churidar pajama in breathable silk blend.',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 16000,
      sellingPrice: 28000,
      rentalPrice: 2500,
      securityDeposit: 4000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section C - Haldi Racks',
      supplierId: 'sup-003',
      createdDate: '2026-02-01',
      featured: false,
      tags: ['Haldi', 'Mirror Work', 'Yellow'],
    },
    {
      id: 'prod-006',
      sku: 'BG-MIDNIGHT-006',
      name: 'Midnight Blue Italian Silk Jodhpuri Bandhgala',
      category: 'Bandhgala & Jodhpuri',
      subcategory: 'Bandhgala Suits',
      gender: 'men',
      brand: 'Raymond Royal Luxury',
      designer: 'Jodhpur Heritage Craft',
      color: 'Midnight Navy Blue',
      fabric: 'Italian Super 120s Wool & Mulberry Silk',
      sizes: ['38', '40', '42', '44'],
      style: 'Regal Formal Bandhgala',
      description: 'Structured royal tailored Bandhgala with handcrafted lion crest brass buttons, welt pockets, and matching slim-fit charcoal trousers.',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 32000,
      sellingPrice: 58000,
      rentalPrice: 4800,
      securityDeposit: 7000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section A - Suits Gallery',
      supplierId: 'sup-001',
      createdDate: '2026-02-05',
      featured: false,
      tags: ['Reception', 'Formal', 'Bandhgala'],
    },
    {
      id: 'prod-007',
      sku: 'ACC-GROOM-007',
      name: 'Royal Maharaja Groom Accessories Hamper',
      category: 'Wedding Accessories',
      subcategory: 'Safa & Pagdi',
      gender: 'accessories',
      brand: 'Shahi Shringaar',
      designer: 'Jaipur Gems House',
      color: 'Beige & Maroon Velvet',
      fabric: 'Brocade Silk & Velvet',
      sizes: ['Standard'],
      style: 'Maharaja Accessories Set',
      description: 'Complete groom set containing pre-tied Marwari Safa with antique Kundan Kalgi, pearl layered Mala, brass vintage sword brooch, and zardozi embroidered Mojaris (size 8/9/10).',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 12000,
      sellingPrice: 22000,
      rentalPrice: 1800,
      securityDeposit: 3000,
      type: 'both',
      condition: 'Good',
      location: 'Accessories Glass Cabinet 02',
      supplierId: 'sup-003',
      createdDate: '2026-02-08',
      featured: false,
      tags: ['Safa', 'Kalgi', 'Mojari', 'Groom Accessories'],
    },
    {
      id: 'prod-008',
      sku: 'SR-BANARASI-008',
      name: 'Royal Banarasi Katan Silk Gold Zari Bridal Saree',
      category: 'Designer Saree & Gown',
      subcategory: 'Banarasi Silk',
      gender: 'women',
      brand: 'Varanasi Master Weaves',
      designer: 'Ritu Kumar Heritage',
      color: 'Vermillion Red & Antique Gold',
      fabric: 'Pure Katan Mulberry Silk with Real Gold Zari',
      sizes: ['Free Size'],
      style: 'Traditional Royal Drape',
      description: 'Handwoven in Varanasi over 90 days, featuring traditional Shikargah wildlife motifs, heavy pallu, and unstitched matching brocade blouse piece with sweetheart neckline option.',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 38000,
      sellingPrice: 68000,
      rentalPrice: 5200,
      securityDeposit: 8000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Bridal Vault Showcase 02',
      supplierId: 'sup-004',
      createdDate: '2026-02-10',
      featured: true,
      tags: ['Banarasi', 'Bridal', 'Silk', 'Heritage'],
    },
    {
      id: 'prod-009',
      sku: 'LH-EMERALD-009',
      name: 'Emerald Green Handcrafted Sangeet Mirror Lehenga',
      category: 'Bridal & Designer Lehenga',
      subcategory: 'Mirror Work Sangeet',
      gender: 'women',
      brand: 'Abhinav Mishra Couture',
      designer: 'Surat Zari Guild',
      color: 'Deep Emerald Green',
      fabric: 'Raw Silk & Sheer Organza',
      sizes: ['S', 'M', 'L'],
      style: 'Dramatic 12-Kali High Flared Skirt',
      description: 'Stunning night celebration lehenga with convex real glass mirrors, silver dabka work, matching plunging neckline choli, and featherlight scalloped dupatta.',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 52000,
      sellingPrice: 92000,
      rentalPrice: 7200,
      securityDeposit: 12000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Bridal Section 03',
      supplierId: 'sup-002',
      createdDate: '2026-02-12',
      featured: true,
      tags: ['Sangeet', 'Mirror Work', 'Emerald Green'],
    },
    {
      id: 'prod-010',
      sku: 'SH-ACHKAN-010',
      name: 'Ivory & Rose Gold Raw Silk Achkan Sherwani',
      category: 'Sherwani',
      subcategory: 'Achkan',
      gender: 'men',
      brand: 'Tarun Tahiliani Men',
      designer: 'Jaipur Shahi Tailors',
      color: 'Ivory / Rose Gold',
      fabric: 'Matka Silk with French Knot Embroidery',
      sizes: ['38', '40', '42', '44'],
      style: 'Sleek Fitted Royal Achkan',
      description: 'Understated aristocratic daytime wedding outfit with tonal resham floral vines, rose-cut pearl buttons, and matching churidar in rich dupion silk.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 48000,
      sellingPrice: 88000,
      rentalPrice: 6200,
      securityDeposit: 10000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section A - Groom Showcase Racks',
      supplierId: 'sup-001',
      createdDate: '2026-02-15',
      featured: false,
      tags: ['Day Wedding', 'Achkan', 'Ivory', 'Groom'],
    },
    {
      id: 'prod-011',
      sku: 'TX-CHARCOAL-011',
      name: 'Charcoal Super 130s Silk Satin Shawl Tuxedo',
      category: 'Bandhgala & Jodhpuri',
      subcategory: 'Tuxedos',
      gender: 'men',
      brand: 'Canali Luxury Bespoke',
      designer: 'Boutique Tailoring Studio',
      color: 'Charcoal Grey with Black Lapel',
      fabric: 'Super 130s Merino Wool with Silk Satin Lapels',
      sizes: ['38', '40', '42'],
      style: 'Single Button Black-Tie Tuxedo',
      description: 'Sophisticated cocktail and black-tie reception tuxedo. Includes tuxedo jacket, side-stripe satin trousers, pleated bib dress shirt, and silk bowtie.',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 36000,
      sellingPrice: 65000,
      rentalPrice: 4800,
      securityDeposit: 8000,
      type: 'both',
      condition: 'Excellent',
      location: 'Section A - Suits Gallery',
      supplierId: 'sup-001',
      createdDate: '2026-02-18',
      featured: false,
      tags: ['Tuxedo', 'Cocktail', 'Reception', 'Black Tie'],
    },
    {
      id: 'prod-012',
      sku: 'SH-SHARARA-012',
      name: 'Dusty Rose Organza Peplum Sharara Set',
      category: 'Sharara & Anarkali',
      subcategory: 'Peplum Sharara',
      gender: 'women',
      brand: 'Ridha Couture',
      designer: 'Surat Heritage Crafts',
      color: 'Dusty Rose / Champagne',
      fabric: 'Pure Organza with Gota Patti & Zari Borders',
      sizes: ['S', 'M', 'L'],
      style: 'Tiered Flared Sharara with Peplum Kurti',
      description: 'Lightweight high-glamour sharara ensemble with handcrafted gota patti embroidery, flared tier bottoms, and sheer lightweight dupatta.',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 26000,
      sellingPrice: 45000,
      rentalPrice: 3800,
      securityDeposit: 6000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Women Section 02',
      supplierId: 'sup-002',
      createdDate: '2026-02-20',
      featured: false,
      tags: ['Sharara', 'Sangeet', 'Pastel', 'Organza'],
    },
    {
      id: 'prod-013',
      sku: 'KJ-DHOTI-013',
      name: 'Sunflower Yellow Chanderi Haldi Dhoti Kurta',
      category: 'Kurta Jacket & Haldi Set',
      subcategory: 'Dhoti Kurta',
      gender: 'men',
      brand: 'Vastra Heritage',
      designer: 'Jaipur Shahi Tailors',
      color: 'Sunflower Bright Yellow',
      fabric: 'Chanderi Cotton Silk with Bandhani Dupatta',
      sizes: ['38', '40', '42'],
      style: 'Traditional Pleated Pre-stitched Dhoti Set',
      description: 'Festive Haldi and Pooja outfit with breathable gold buttis, matching embroidered pocket square, and pre-pleated ready-to-wear dhoti.',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 14000,
      sellingPrice: 24000,
      rentalPrice: 2200,
      securityDeposit: 3500,
      type: 'both',
      condition: 'Good',
      location: 'Section C - Haldi Racks',
      supplierId: 'sup-003',
      createdDate: '2026-02-22',
      featured: false,
      tags: ['Haldi', 'Dhoti', 'Yellow', 'Traditional'],
    },
    {
      id: 'prod-014',
      sku: 'GW-COCKTAIL-014',
      name: 'Royal Marsala Wine Indo-Western Cocktail Gown',
      category: 'Designer Saree & Gown',
      subcategory: 'Cocktail Gowns',
      gender: 'women',
      brand: 'Gaurav Gupta Atelier',
      designer: 'Delhi Couture Studio',
      color: 'Deep Marsala Wine',
      fabric: 'Sculpted Neoprene & Silk Tulle',
      sizes: ['S', 'M', 'L'],
      style: 'Sculptural Flared Gown with Sweep Train',
      description: 'Showstopper cocktail reception gown with 3D structural shoulder wire drape, crystalline bugle beads, and dramatic sweeping flare.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 58000,
      sellingPrice: 110000,
      rentalPrice: 8500,
      securityDeposit: 14000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Bridal Vault Showcase 03',
      supplierId: 'sup-002',
      createdDate: '2026-02-24',
      featured: true,
      tags: ['Cocktail', 'Gown', 'Reception', 'Designer'],
    },
    {
      id: 'prod-015',
      sku: 'ACC-JADAU-015',
      name: 'Heritage Rajputana Jadau Pearl Kalgi & Mala Set',
      category: 'Wedding Accessories',
      subcategory: 'Kalgi & Brooch',
      gender: 'accessories',
      brand: 'Tanishq Royal Heritage Line',
      designer: 'Jaipur Gems House',
      color: 'Antique Gold & Basra Pearl',
      fabric: 'Brass Alloy with 24K Gold Micro-Plating',
      sizes: ['Standard'],
      style: 'Imperial Turban Ornament Set',
      description: 'Authentic Marwari Kalgi encrusted with un-cut polki glass stones, green meenakari enamel work, and 5-layered real freshwater pearl Mala necklace.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 9000,
      sellingPrice: 16500,
      rentalPrice: 1400,
      securityDeposit: 2500,
      type: 'both',
      condition: 'Excellent',
      location: 'Accessories Glass Cabinet 01',
      supplierId: 'sup-003',
      createdDate: '2026-02-25',
      featured: false,
      tags: ['Kalgi', 'Pearl Mala', 'Groom Jewelry'],
    },
    {
      id: 'prod-016',
      sku: 'ACC-DUPATTA-016',
      name: 'Heavy Zardozi Velvet Bridal Veil & Dupatta',
      category: 'Wedding Accessories',
      subcategory: 'Stole / Dupatta',
      gender: 'accessories',
      brand: 'Sabyasachi Heritage Veil',
      designer: 'Lucknowi Zari Ghar',
      color: 'Crimson Vermillion Red',
      fabric: 'Micro Velvet with Pure Silk Scalloped Edge',
      sizes: ['2.75 Meters'],
      style: 'Royal Second Dupatta Drape',
      description: 'Second head-veil for brides featuring Sada Saubhagyavati Bhava Sanskrit mantra hand-embroidered along the 4-sided zardozi border.',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 15000,
      sellingPrice: 28000,
      rentalPrice: 2500,
      securityDeposit: 4000,
      type: 'both',
      condition: 'Pristine Luxury',
      location: 'Accessories Glass Cabinet 03',
      supplierId: 'sup-002',
      createdDate: '2026-02-26',
      featured: false,
      tags: ['Bridal Dupatta', 'Veil', 'Zardozi'],
    },
    {
      id: 'prod-017',
      sku: 'ACC-SAFA-017',
      name: 'Pre-Tied Brocade Silk Royal Safa with Kalgi Mount',
      category: 'Wedding Accessories',
      subcategory: 'Safa & Pagdi',
      gender: 'accessories',
      brand: 'Shahi Pagdi Emporium',
      designer: 'Jaipur Shahi Tailors',
      color: 'Beige Champagne with Gold Thread',
      fabric: 'Chanderi Brocade Silk',
      sizes: ['21.5-23 Inch Adjustable'],
      style: 'Pre-tied Structured Marwari Pagdi',
      description: 'Ready-to-wear pre-tied luxury wedding safa with cushioned inner circumference, pleated front drape, and secure kalgi brooch bracket.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 4500,
      sellingPrice: 8500,
      rentalPrice: 950,
      securityDeposit: 1500,
      type: 'both',
      condition: 'Good',
      location: 'Accessories Racks B-1',
      supplierId: 'sup-003',
      createdDate: '2026-02-26',
      featured: false,
      tags: ['Safa', 'Pagdi', 'Groom Turban'],
    },
    {
      id: 'prod-018',
      sku: 'ACC-MOJARI-018',
      name: 'Handcrafted Embroidered Velvet Jodhpuri Mojari',
      category: 'Wedding Accessories',
      subcategory: 'Mojari',
      gender: 'accessories',
      brand: 'Jodhpur Shahi Shoes',
      designer: 'Jodhpur Heritage Craft',
      color: 'Deep Maroon & Gold',
      fabric: 'Genuine Leather Base with Velvet Zari Top',
      sizes: ['8', '9', '10'],
      style: 'Curled Toe Royal Jutti',
      description: 'Authentic royal mojari with cushioned insole for daylong wedding comfort, curled traditional toe, and intricate antique dabka embroidery.',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
      ],
      purchasePrice: 3200,
      sellingPrice: 5800,
      rentalPrice: 700,
      securityDeposit: 1200,
      type: 'both',
      condition: 'Good',
      location: 'Shoe Vault Box 01',
      supplierId: 'sup-003',
      createdDate: '2026-02-26',
      featured: false,
      tags: ['Mojari', 'Jutti', 'Groom Shoes'],
    },
  ];

  inventoryItems: PhysicalInventoryItem[] = [
    // Product 1 (Imperial Crimson Sherwani)
    {
      id: 'SH001',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-38',
      barcode: '890123400101',
      size: '38',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-1',
      rentalCount: 11,
      lastRentalDate: '2026-07-28',
      lastCleaningDate: '2026-08-01',
      totalRevenue: 71500,
      cleaningCount: 11,
      repairsCount: 1,
      notes: 'Zari wire retightened in March 2026. Immaculate condition.',
    },
    {
      id: 'SH002',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-40',
      barcode: '890123400102',
      size: '40',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Booked',
      currentLocation: 'Rack A-2 (Reserved)',
      rentalCount: 18,
      lastRentalDate: '2026-08-10',
      lastCleaningDate: '2026-08-14',
      nextAvailableDate: '2026-09-02',
      totalRevenue: 117000,
      cleaningCount: 18,
      repairsCount: 2,
      notes: 'Reserved for Vikram Rathore wedding.',
    },
    {
      id: 'SH003',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-42',
      barcode: '890123400103',
      size: '42',
      color: 'Crimson Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-3',
      rentalCount: 14,
      lastRentalDate: '2026-08-05',
      lastCleaningDate: '2026-08-09',
      totalRevenue: 91000,
      cleaningCount: 14,
      repairsCount: 0,
      notes: 'Ready for immediate trial or pickup.',
    },
    {
      id: 'SH004',
      productId: 'prod-001',
      sku: 'SH-ROYAL-001-44',
      barcode: '890123400104',
      size: '44',
      color: 'Crimson Gold',
      condition: 'Good',
      status: 'Cleaning',
      currentLocation: 'Dry Cleaner Express Unit',
      rentalCount: 8,
      lastRentalDate: '2026-08-20',
      lastCleaningDate: '2026-08-22',
      nextAvailableDate: '2026-08-28',
      totalRevenue: 52000,
      cleaningCount: 8,
      repairsCount: 1,
      notes: 'Dispatched to Sparkle Drycleaners for ozone steam press.',
    },

    // Product 2 (Ruby Velvet Bridal Lehenga)
    {
      id: 'LH001',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-S',
      barcode: '890123400201',
      size: 'S',
      color: 'Deep Ruby Red',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-1',
      rentalCount: 9,
      lastRentalDate: '2026-08-02',
      lastCleaningDate: '2026-08-06',
      totalRevenue: 85500,
      cleaningCount: 9,
      repairsCount: 1,
      notes: 'Includes padded 34B blouse with drawstring tassels.',
    },
    {
      id: 'LH002',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-M',
      barcode: '890123400202',
      size: 'M',
      color: 'Deep Ruby Red',
      condition: 'Excellent',
      status: 'Rented',
      currentLocation: 'With Customer (Devangi Joshi)',
      rentalCount: 16,
      lastRentalDate: '2026-08-22',
      lastCleaningDate: '2026-08-18',
      nextAvailableDate: '2026-08-30',
      totalRevenue: 152000,
      cleaningCount: 16,
      repairsCount: 3,
      notes: 'Active rental in Kensville destination wedding.',
    },
    {
      id: 'LH003',
      productId: 'prod-002',
      sku: 'LH-BRIDAL-002-L',
      barcode: '890123400203',
      size: 'L',
      color: 'Deep Ruby Red',
      condition: 'Good',
      status: 'Alteration',
      currentLocation: 'Tailor Master Desk - Ramesh Master',
      rentalCount: 12,
      lastRentalDate: '2026-08-12',
      lastCleaningDate: '2026-08-16',
      nextAvailableDate: '2026-08-29',
      totalRevenue: 114000,
      cleaningCount: 12,
      repairsCount: 1,
      notes: 'Blouse side margin release by 1.2 inches for upcoming wedding.',
    },

    // Product 3 (Pastel Indo-Western)
    {
      id: 'IW001',
      productId: 'prod-003',
      sku: 'IW-PEACH-003-40',
      barcode: '890123400301',
      size: '40',
      color: 'Blush Peach',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack B-1',
      rentalCount: 7,
      lastRentalDate: '2026-07-30',
      lastCleaningDate: '2026-08-04',
      totalRevenue: 29400,
      cleaningCount: 7,
      repairsCount: 0,
    },
    {
      id: 'IW002',
      productId: 'prod-003',
      sku: 'IW-PEACH-003-42',
      barcode: '890123400302',
      size: '42',
      color: 'Blush Peach',
      condition: 'Excellent',
      status: 'Booked',
      currentLocation: 'Rack B-2',
      rentalCount: 9,
      lastRentalDate: '2026-08-08',
      lastCleaningDate: '2026-08-12',
      nextAvailableDate: '2026-09-05',
      totalRevenue: 37800,
      cleaningCount: 9,
      repairsCount: 0,
    },

    // Product 4 (Chikankari Pastel Lehenga)
    {
      id: 'LH004',
      productId: 'prod-004',
      sku: 'LH-PASTEL-004-M',
      barcode: '890123400401',
      size: 'M',
      color: 'Mint Green',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-4',
      rentalCount: 6,
      lastRentalDate: '2026-08-01',
      lastCleaningDate: '2026-08-05',
      totalRevenue: 34800,
      cleaningCount: 6,
      repairsCount: 0,
    },
    {
      id: 'LH005',
      productId: 'prod-004',
      sku: 'LH-PASTEL-004-L',
      barcode: '890123400402',
      size: 'L',
      color: 'Mint Green',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-5',
      rentalCount: 5,
      lastRentalDate: '2026-07-25',
      lastCleaningDate: '2026-07-29',
      totalRevenue: 29000,
      cleaningCount: 5,
      repairsCount: 0,
    },

    // Product 5 (Haldi Kurta Jacket)
    {
      id: 'KJ001',
      productId: 'prod-005',
      sku: 'KJ-HALDI-005-40',
      barcode: '890123400501',
      size: '40',
      color: 'Mustard Yellow',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack C-1',
      rentalCount: 15,
      lastRentalDate: '2026-08-15',
      lastCleaningDate: '2026-08-19',
      totalRevenue: 37500,
      cleaningCount: 15,
      repairsCount: 1,
    },
    {
      id: 'KJ002',
      productId: 'prod-005',
      sku: 'KJ-HALDI-005-42',
      barcode: '890123400502',
      size: '42',
      color: 'Mustard Yellow',
      condition: 'Minor Damage',
      status: 'Repair',
      currentLocation: 'Tailoring Section Table 2',
      rentalCount: 12,
      lastRentalDate: '2026-08-18',
      lastCleaningDate: '2026-08-20',
      nextAvailableDate: '2026-08-30',
      totalRevenue: 30000,
      cleaningCount: 12,
      repairsCount: 3,
      notes: '2 small glass mirrors loose on right chest pocket. Under repair by Suresh.',
    },

    // Product 6 (Bandhgala)
    {
      id: 'BG001',
      productId: 'prod-006',
      sku: 'BG-MIDNIGHT-006-40',
      barcode: '890123400601',
      size: '40',
      color: 'Midnight Navy Blue',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-5',
      rentalCount: 8,
      lastRentalDate: '2026-08-04',
      lastCleaningDate: '2026-08-08',
      totalRevenue: 38400,
      cleaningCount: 8,
      repairsCount: 0,
    },
    {
      id: 'BG002',
      productId: 'prod-006',
      sku: 'BG-MIDNIGHT-006-42',
      barcode: '890123400602',
      size: '42',
      color: 'Midnight Navy Blue',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-6',
      rentalCount: 10,
      lastRentalDate: '2026-08-02',
      lastCleaningDate: '2026-08-06',
      totalRevenue: 48000,
      cleaningCount: 10,
      repairsCount: 0,
    },

    // Product 7 (Groom Accessories)
    {
      id: 'ACC001',
      productId: 'prod-007',
      sku: 'ACC-GROOM-007-STD',
      barcode: '890123400701',
      size: 'Standard',
      color: 'Beige & Maroon',
      condition: 'Good',
      status: 'Available',
      currentLocation: 'Accessory Showcase 01',
      rentalCount: 14,
      lastRentalDate: '2026-08-11',
      lastCleaningDate: '2026-08-13',
      totalRevenue: 25200,
      cleaningCount: 14,
      repairsCount: 1,
    },

    // Product 8 (Banarasi Saree)
    {
      id: 'SR001',
      productId: 'prod-008',
      sku: 'SR-BANARASI-008-STD',
      barcode: '890123400801',
      size: 'Free Size',
      color: 'Vermillion Red',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Bridal Vault Showcase 02',
      rentalCount: 7,
      lastRentalDate: '2026-08-07',
      lastCleaningDate: '2026-08-11',
      totalRevenue: 36400,
      cleaningCount: 7,
      repairsCount: 0,
      notes: 'Accompanied by gold tissue fall & roll-press finish.',
    },

    // Product 9 (Emerald Green Sangeet Lehenga)
    {
      id: 'LH006',
      productId: 'prod-009',
      sku: 'LH-EMERALD-009-S',
      barcode: '890123400901',
      size: 'S',
      color: 'Emerald Green',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Bridal Section 03',
      rentalCount: 8,
      lastRentalDate: '2026-08-12',
      lastCleaningDate: '2026-08-15',
      totalRevenue: 57600,
      cleaningCount: 8,
      repairsCount: 0,
    },
    {
      id: 'LH007',
      productId: 'prod-009',
      sku: 'LH-EMERALD-009-M',
      barcode: '890123400902',
      size: 'M',
      color: 'Emerald Green',
      condition: 'Excellent',
      status: 'Booked',
      currentLocation: 'Bridal Section 03 (Reserved)',
      rentalCount: 11,
      lastRentalDate: '2026-08-16',
      lastCleaningDate: '2026-08-19',
      nextAvailableDate: '2026-09-04',
      totalRevenue: 79200,
      cleaningCount: 11,
      repairsCount: 1,
    },

    // Product 10 (Ivory Achkan Sherwani)
    {
      id: 'SH005',
      productId: 'prod-010',
      sku: 'SH-ACHKAN-010-40',
      barcode: '890123401001',
      size: '40',
      color: 'Ivory Rose Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-4',
      rentalCount: 6,
      lastRentalDate: '2026-08-01',
      lastCleaningDate: '2026-08-05',
      totalRevenue: 37200,
      cleaningCount: 6,
      repairsCount: 0,
    },
    {
      id: 'SH006',
      productId: 'prod-010',
      sku: 'SH-ACHKAN-010-42',
      barcode: '890123401002',
      size: '42',
      color: 'Ivory Rose Gold',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Rack A-4',
      rentalCount: 8,
      lastRentalDate: '2026-08-09',
      lastCleaningDate: '2026-08-13',
      totalRevenue: 49600,
      cleaningCount: 8,
      repairsCount: 0,
    },

    // Product 11 (Tuxedo)
    {
      id: 'TX001',
      productId: 'prod-011',
      sku: 'TX-CHARCOAL-011-40',
      barcode: '890123401101',
      size: '40',
      color: 'Charcoal Grey',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Section A - Tuxedos',
      rentalCount: 5,
      lastRentalDate: '2026-08-03',
      lastCleaningDate: '2026-08-06',
      totalRevenue: 24000,
      cleaningCount: 5,
      repairsCount: 0,
    },

    // Product 12 (Peplum Sharara)
    {
      id: 'SH007',
      productId: 'prod-012',
      sku: 'SH-SHARARA-012-M',
      barcode: '890123401201',
      size: 'M',
      color: 'Dusty Rose',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Women Section 02',
      rentalCount: 7,
      lastRentalDate: '2026-08-10',
      lastCleaningDate: '2026-08-14',
      totalRevenue: 26600,
      cleaningCount: 7,
      repairsCount: 0,
    },

    // Product 13 (Haldi Dhoti Kurta)
    {
      id: 'KJ003',
      productId: 'prod-013',
      sku: 'KJ-DHOTI-013-40',
      barcode: '890123401301',
      size: '40',
      color: 'Sunflower Yellow',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Section C - Haldi Racks',
      rentalCount: 9,
      lastRentalDate: '2026-08-14',
      lastCleaningDate: '2026-08-17',
      totalRevenue: 19800,
      cleaningCount: 9,
      repairsCount: 0,
    },

    // Product 14 (Wine Cocktail Gown)
    {
      id: 'GW001',
      productId: 'prod-014',
      sku: 'GW-COCKTAIL-014-M',
      barcode: '890123401401',
      size: 'M',
      color: 'Marsala Wine',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Vault Box V-6',
      rentalCount: 6,
      lastRentalDate: '2026-08-06',
      lastCleaningDate: '2026-08-10',
      totalRevenue: 51000,
      cleaningCount: 6,
      repairsCount: 0,
    },

    // Product 15 (Jadau Kalgi)
    {
      id: 'ACC002',
      productId: 'prod-015',
      sku: 'ACC-JADAU-015-STD',
      barcode: '890123401501',
      size: 'Standard',
      color: 'Gold & Pearl',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Glass Cabinet 01',
      rentalCount: 13,
      lastRentalDate: '2026-08-15',
      lastCleaningDate: '2026-08-16',
      totalRevenue: 18200,
      cleaningCount: 13,
      repairsCount: 0,
    },

    // Product 16 (Velvet Veil)
    {
      id: 'ACC003',
      productId: 'prod-016',
      sku: 'ACC-DUPATTA-016-STD',
      barcode: '890123401601',
      size: '2.75M',
      color: 'Crimson Red',
      condition: 'Excellent',
      status: 'Available',
      currentLocation: 'Glass Cabinet 03',
      rentalCount: 10,
      lastRentalDate: '2026-08-11',
      lastCleaningDate: '2026-08-14',
      totalRevenue: 25000,
      cleaningCount: 10,
      repairsCount: 0,
    },

    // Product 17 (Brocade Safa)
    {
      id: 'ACC004',
      productId: 'prod-017',
      sku: 'ACC-SAFA-017-STD',
      barcode: '890123401701',
      size: 'Adjustable',
      color: 'Champagne Beige',
      condition: 'Good',
      status: 'Available',
      currentLocation: 'Accessory Racks B-1',
      rentalCount: 16,
      lastRentalDate: '2026-08-18',
      lastCleaningDate: '2026-08-20',
      totalRevenue: 15200,
      cleaningCount: 16,
      repairsCount: 0,
    },

    // Product 18 (Mojari)
    {
      id: 'ACC005',
      productId: 'prod-018',
      sku: 'ACC-MOJARI-018-9',
      barcode: '890123401801',
      size: '9',
      color: 'Maroon & Gold',
      condition: 'Good',
      status: 'Available',
      currentLocation: 'Shoe Vault Box 01',
      rentalCount: 11,
      lastRentalDate: '2026-08-12',
      lastCleaningDate: '2026-08-14',
      totalRevenue: 7700,
      cleaningCount: 11,
      repairsCount: 1,
    },
  ];

  customers: Customer[] = [
    {
      id: 'cust-001',
      customerId: 'CUST-2026-001',
      name: 'Vikram & Ananya Rathore',
      phone: '+91 98250 14892',
      whatsapp: '+91 98250 14892',
      email: 'vikram.rathore@gmail.com',
      address: '702, Shivalik Highstreet, Judges Bungalow Road, Bodakdev',
      city: 'Ahmedabad',
      dateOfBirth: '1995-11-14',
      weddingDate: '2026-08-31',
      notes: 'VIP Groom customer. Grand wedding at Jagmandir Palace, Udaipur.',
      menMeasurements: {
        height: "5'11\"",
        weight: '76 kg',
        chest: 40.5,
        waist: 33,
        shoulder: 18.5,
        sleeveLength: 25.5,
        neck: 16,
        kurtaLength: 42,
        sherwaniLength: 43.5,
        pantLength: 41,
        thigh: 23,
        bottomOpening: 14.5,
        shoeSize: '9',
      },
      womenMeasurements: {
        height: "5'6\"",
        bust: 35,
        waist: 28,
        hip: 38,
        shoulder: 15,
        sleeveLength: 11,
        blouseLength: 14.5,
        lehengaWaist: 29,
        lehengaLength: 42,
        dupattaLength: '2.6m',
        shoeSize: '6',
      },
      totalBookings: 2,
      totalPurchases: 1,
      outstandingAmount: 4500,
      totalSpent: 32235,
      createdDate: '2026-04-10',
    },
    {
      id: 'cust-002',
      customerId: 'CUST-2026-002',
      name: 'Devangi & Hardik Joshi',
      phone: '+91 98791 22340',
      whatsapp: '+91 98791 22340',
      email: 'devangi.joshi@outlook.com',
      address: 'B-404, Orchid Elegance, South Bopal',
      city: 'Ahmedabad',
      dateOfBirth: '1997-03-22',
      weddingDate: '2026-08-26',
      notes: 'Bridal customer for 4-day wedding rituals.',
      womenMeasurements: {
        height: "5'4\"",
        bust: 36,
        waist: 30,
        hip: 39,
        shoulder: 14.5,
        sleeveLength: 10.5,
        blouseLength: 15,
        lehengaWaist: 31,
        lehengaLength: 40.5,
        dupattaLength: '2.5m',
        shoeSize: '7',
      },
      totalBookings: 3,
      totalPurchases: 0,
      outstandingAmount: 0,
      totalSpent: 28500,
      createdDate: '2026-05-18',
    },
    {
      id: 'cust-003',
      customerId: 'CUST-2026-003',
      name: 'Chirag Singhania',
      phone: '+91 99099 88123',
      whatsapp: '+91 99099 88123',
      email: 'chirag.s@singhaniaexports.in',
      address: '22, Gulmohar Park, Satellite',
      city: 'Ahmedabad',
      dateOfBirth: '1992-08-05',
      weddingDate: '2026-09-15',
      notes: 'Brother of the bride. Needs multiple event outfits.',
      menMeasurements: {
        height: "6'0\"",
        weight: '82 kg',
        chest: 42,
        waist: 35,
        shoulder: 19,
        sleeveLength: 26,
        neck: 16.5,
        kurtaLength: 43,
        sherwaniLength: 44,
        pantLength: 42,
        thigh: 24,
        bottomOpening: 15,
        shoeSize: '10',
      },
      totalBookings: 1,
      totalPurchases: 2,
      outstandingAmount: 2000,
      totalSpent: 26550,
      createdDate: '2026-06-02',
    },
    {
      id: 'cust-004',
      customerId: 'CUST-2026-004',
      name: 'Rohan & Simran Mehta',
      phone: '+91 98201 55678',
      whatsapp: '+91 98201 55678',
      email: 'rohan.mehta@mehtacorp.com',
      address: 'Flat 14B, Samudra Mahal, Worli Seaface',
      city: 'Mumbai',
      weddingDate: '2026-09-18',
      notes: 'Destination wedding in Goa. Booked pastel lehenga and indo-western.',
      menMeasurements: {
        height: "5'10\"",
        chest: 41,
        waist: 34,
        shoulder: 18.5,
        sleeveLength: 25,
        sherwaniLength: 43,
        pantLength: 40.5,
      },
      womenMeasurements: {
        height: "5'5\"",
        bust: 34,
        waist: 28,
        hip: 37,
        blouseLength: 14,
        lehengaLength: 41,
      },
      totalBookings: 1,
      totalPurchases: 0,
      outstandingAmount: 0,
      totalSpent: 12500,
      createdDate: '2026-06-15',
    },
    {
      id: 'cust-005',
      customerId: 'CUST-2026-005',
      name: 'Kavita & Aditya Singhal',
      phone: '+91 94140 88991',
      whatsapp: '+91 94140 88991',
      email: 'aditya.singhal@jaipurjewels.com',
      address: 'Civil Lines, Near Raj Bhavan',
      city: 'Jaipur',
      weddingDate: '2026-09-24',
      notes: 'Palace wedding. Fitting scheduled for master tailor consultation.',
      womenMeasurements: {
        height: "5'7\"",
        bust: 37,
        waist: 30,
        hip: 40,
        blouseLength: 15.5,
        lehengaLength: 43,
      },
      totalBookings: 1,
      totalPurchases: 1,
      outstandingAmount: 0,
      totalSpent: 21500,
      createdDate: '2026-06-28',
    },
    {
      id: 'cust-006',
      customerId: 'CUST-2026-006',
      name: 'Pranav & Tanvi Shah (NRI UK)',
      phone: '+91 97129 33440',
      whatsapp: '+44 7911 123456',
      email: 'pranav.shah@londonlaw.co.uk',
      address: 'A-201, Iscon Platinum, Bopal Ambli Road',
      city: 'Ahmedabad / London',
      weddingDate: '2026-08-25',
      notes: 'NRI couple wedding. Outfits currently in active rental.',
      menMeasurements: {
        height: "6'1\"",
        chest: 42,
        waist: 34,
        shoulder: 19,
        sherwaniLength: 44.5,
      },
      totalBookings: 1,
      totalPurchases: 0,
      outstandingAmount: 0,
      totalSpent: 16500,
      createdDate: '2026-07-02',
    },
    {
      id: 'cust-007',
      customerId: 'CUST-2026-007',
      name: 'Meera & Siddharth Deshmukh',
      phone: '+91 98220 77112',
      whatsapp: '+91 98220 77112',
      email: 'siddharth.deshmukh@tcs.com',
      address: 'Bungalow 9, Prabhat Road, Lane 4',
      city: 'Surat',
      weddingDate: '2026-08-20',
      notes: 'Return was due on 23 August. Reminder message sent for late return.',
      womenMeasurements: {
        height: "5'3\"",
        bust: 35,
        waist: 29,
        hip: 38,
        lehengaLength: 40,
      },
      totalBookings: 1,
      totalPurchases: 0,
      outstandingAmount: 0,
      totalSpent: 8500,
      createdDate: '2026-07-10',
    },
    {
      id: 'cust-008',
      customerId: 'CUST-2026-008',
      name: 'Arjun & Radhika Kapoor',
      phone: '+91 98100 44321',
      whatsapp: '+91 98100 44321',
      email: 'arjun.kapoor@delhifinance.in',
      address: '45, Golf Links',
      city: 'Delhi',
      weddingDate: '2026-09-05',
      notes: 'Groom and bride matching set ready for showroom pickup.',
      menMeasurements: {
        height: "5'11\"",
        chest: 40,
        waist: 32,
        shoulder: 18,
        sherwaniLength: 43,
      },
      womenMeasurements: {
        height: "5'6\"",
        bust: 34,
        waist: 27,
        hip: 37,
        lehengaLength: 42,
      },
      totalBookings: 1,
      totalPurchases: 0,
      outstandingAmount: 0,
      totalSpent: 18000,
      createdDate: '2026-07-20',
    },
  ];

  bookings: Booking[] = [
    {
      id: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      customerPhone: '+91 98250 14892',
      customerWhatsapp: '+91 98250 14892',
      weddingTitle: 'Vikram & Ananya Royal Wedding',
      events: [
        {
          id: 'ev-1',
          name: 'Sangeet',
          eventDate: '2026-08-30',
          eventTime: '07:30 PM',
          venue: 'The Grand Bhagwati, SG Highway',
        },
        {
          id: 'ev-2',
          name: 'Wedding',
          eventDate: '2026-08-31',
          eventTime: '11:00 AM',
          venue: 'Umaid Bhawan Grounds / YMCA Club',
        },
      ],
      items: [
        {
          productId: 'prod-001',
          physicalItemId: 'SH002',
          productName: 'Imperial Crimson & Gold Zardozi Sherwani',
          sku: 'SH-ROYAL-001-40',
          size: '40',
          rentalPrice: 6500,
          securityDeposit: 10000,
          eventName: 'Wedding',
          alterationDetails: 'Sleeve hem length reduced by 0.5 inch.',
        },
        {
          productId: 'prod-003',
          physicalItemId: 'IW002',
          productName: 'Pastel Blush Peach Asymmetric Indo-Western Set',
          sku: 'IW-PEACH-003-42',
          size: '42',
          rentalPrice: 4200,
          securityDeposit: 6000,
          eventName: 'Sangeet',
        },
      ],
      rentalStartDate: '2026-08-29',
      rentalEndDate: '2026-09-02',
      pickupDate: '2026-08-29',
      returnDate: '2026-09-02',
      deliveryAddress: 'Store Pickup Scheduled by Vikram',
      rentalAmount: 10700,
      securityDeposit: 16000,
      discount: 1000,
      taxRate: 5,
      taxAmount: 485,
      totalAmount: 10185,
      advancePaid: 5000,
      remainingAmount: 5185,
      depositCollected: 16000,
      depositHeld: 16000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Ready',
      paymentStatus: 'Partial',
      notes: 'Customer requested matching pagdi on pickup.',
      createdDate: '2026-08-15',
    },
    {
      id: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      customerPhone: '+91 98791 22340',
      customerWhatsapp: '+91 98791 22340',
      weddingTitle: 'Devangi Joshi Destination Wedding',
      events: [
        {
          id: 'ev-3',
          name: 'Wedding',
          eventDate: '2026-08-26',
          venue: 'Kensville Golf & Country Club',
        },
      ],
      items: [
        {
          productId: 'prod-002',
          physicalItemId: 'LH002',
          productName: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
          sku: 'LH-BRIDAL-002-M',
          size: 'M',
          rentalPrice: 9500,
          securityDeposit: 15000,
          eventName: 'Wedding',
        },
      ],
      rentalStartDate: '2026-08-24',
      rentalEndDate: '2026-08-28',
      pickupDate: '2026-08-24',
      returnDate: '2026-08-28',
      rentalAmount: 9500,
      securityDeposit: 15000,
      discount: 500,
      taxRate: 5,
      taxAmount: 450,
      totalAmount: 9450,
      advancePaid: 9450,
      remainingAmount: 0,
      depositCollected: 15000,
      depositHeld: 15000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Active Rental',
      paymentStatus: 'Paid',
      notes: 'Outfit currently in active rental. Scheduled return on 28 Aug.',
      createdDate: '2026-08-10',
    },
    {
      id: 'bk-003',
      bookingNumber: 'BK-2026-0803',
      customerId: 'cust-005',
      customerName: 'Kavita & Aditya Singhal',
      customerPhone: '+91 94140 88991',
      customerWhatsapp: '+91 94140 88991',
      weddingTitle: 'Singhal Royal Heritage Nuptials',
      events: [
        {
          id: 'ev-4',
          name: 'Wedding',
          eventDate: '2026-09-24',
          venue: 'Rambagh Palace, Jaipur',
        },
      ],
      items: [
        {
          productId: 'prod-002',
          physicalItemId: 'LH003',
          productName: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
          sku: 'LH-BRIDAL-002-L',
          size: 'L',
          rentalPrice: 9500,
          securityDeposit: 15000,
          eventName: 'Wedding',
          alterationDetails: 'Release side seam allowance by 1.2 inches for comfortable chest fit.',
        },
      ],
      rentalStartDate: '2026-09-22',
      rentalEndDate: '2026-09-26',
      pickupDate: '2026-09-22',
      returnDate: '2026-09-26',
      deliveryAddress: 'Jaipur Delivery via Express Valet',
      rentalAmount: 9500,
      securityDeposit: 15000,
      discount: 0,
      taxRate: 5,
      taxAmount: 475,
      totalAmount: 9975,
      advancePaid: 5000,
      remainingAmount: 4975,
      depositCollected: 15000,
      depositHeld: 15000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Alterations',
      paymentStatus: 'Partial',
      notes: 'Master tailor alteration in progress.',
      createdDate: '2026-08-20',
    },
    {
      id: 'bk-004',
      bookingNumber: 'BK-2026-0804',
      customerId: 'cust-006',
      customerName: 'Pranav & Tanvi Shah (NRI UK)',
      customerPhone: '+91 97129 33440',
      customerWhatsapp: '+44 7911 123456',
      weddingTitle: 'Tanvi & Pranav Gujarati Wedding',
      events: [
        {
          id: 'ev-5',
          name: 'Wedding',
          eventDate: '2026-08-27',
          venue: 'Club Babylon, Ring Road',
        },
      ],
      items: [
        {
          productId: 'prod-009',
          physicalItemId: 'LH007',
          productName: 'Emerald Green Handcrafted Sangeet Mirror Lehenga',
          sku: 'LH-EMERALD-009-M',
          size: 'M',
          rentalPrice: 7200,
          securityDeposit: 12000,
          eventName: 'Sangeet',
        },
      ],
      rentalStartDate: '2026-08-25',
      rentalEndDate: '2026-08-29',
      pickupDate: '2026-08-25',
      returnDate: '2026-08-29',
      deliveryAddress: 'Iscon Platinum Handover',
      rentalAmount: 7200,
      securityDeposit: 12000,
      discount: 0,
      taxRate: 5,
      taxAmount: 360,
      totalAmount: 7560,
      advancePaid: 7560,
      remainingAmount: 0,
      depositCollected: 12000,
      depositHeld: 12000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Active Rental',
      paymentStatus: 'Paid',
      notes: 'Outfits collected on 25 Aug for destination events.',
      createdDate: '2026-08-12',
    },
    {
      id: 'bk-005',
      bookingNumber: 'BK-2026-0805',
      customerId: 'cust-007',
      customerName: 'Meera & Siddharth Deshmukh',
      customerPhone: '+91 98220 77112',
      customerWhatsapp: '+91 98220 77112',
      weddingTitle: 'Deshmukh Wedding Celebrations',
      events: [
        {
          id: 'ev-6',
          name: 'Reception',
          eventDate: '2026-08-21',
          venue: 'Avadh Utopia, Surat',
        },
      ],
      items: [
        {
          productId: 'prod-006',
          physicalItemId: 'BG002',
          productName: 'Midnight Blue Italian Silk Jodhpuri Bandhgala',
          sku: 'BG-MIDNIGHT-006-42',
          size: '42',
          rentalPrice: 4800,
          securityDeposit: 7000,
          eventName: 'Reception',
        },
      ],
      rentalStartDate: '2026-08-20',
      rentalEndDate: '2026-08-23',
      pickupDate: '2026-08-20',
      returnDate: '2026-08-23', // Past date -> triggers Overdue alert!
      deliveryAddress: 'Surat Express Handover',
      rentalAmount: 4800,
      securityDeposit: 7000,
      discount: 300,
      taxRate: 5,
      taxAmount: 225,
      totalAmount: 4725,
      advancePaid: 4725,
      remainingAmount: 0,
      depositCollected: 7000,
      depositHeld: 7000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Active Rental', // overdue!
      paymentStatus: 'Paid',
      notes: 'Customer notified via WhatsApp reminder that return is overdue.',
      createdDate: '2026-08-05',
    },
    {
      id: 'bk-006',
      bookingNumber: 'BK-2026-0806',
      customerId: 'cust-008',
      customerName: 'Arjun & Radhika Kapoor',
      customerPhone: '+91 98100 44321',
      customerWhatsapp: '+91 98100 44321',
      weddingTitle: 'Kapoor Big Fat Wedding',
      events: [
        {
          id: 'ev-7',
          name: 'Wedding',
          eventDate: '2026-09-05',
          venue: 'The Leela Palace, Udaipur',
        },
      ],
      items: [
        {
          productId: 'prod-010',
          physicalItemId: 'SH005',
          productName: 'Ivory & Rose Gold Raw Silk Achkan Sherwani',
          sku: 'SH-ACHKAN-010-40',
          size: '40',
          rentalPrice: 6200,
          securityDeposit: 10000,
          eventName: 'Wedding',
        },
      ],
      rentalStartDate: '2026-09-03',
      rentalEndDate: '2026-09-07',
      pickupDate: '2026-09-03',
      returnDate: '2026-09-07',
      deliveryAddress: 'Store Pickup',
      rentalAmount: 6200,
      securityDeposit: 10000,
      discount: 200,
      taxRate: 5,
      taxAmount: 300,
      totalAmount: 6300,
      advancePaid: 3000,
      remainingAmount: 3300,
      depositCollected: 10000,
      depositHeld: 10000,
      depositRefunded: 0,
      depositDeducted: 0,
      bookingStatus: 'Confirmed',
      paymentStatus: 'Partial',
      notes: 'Advance received. Final trial scheduled for 2 September.',
      createdDate: '2026-08-22',
    },
  ];

  alterations: AlterationTask[] = [
    {
      id: 'alt-001',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram Rathore',
      customerPhone: '+91 98250 14892',
      productId: 'prod-001',
      productName: 'Imperial Crimson & Gold Zardozi Sherwani',
      physicalItemId: 'SH002',
      size: '40',
      alterationType: 'Sleeve Length Shortening',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      tailorName: 'Rameshbhai Darji',
      dueDate: '2026-08-28',
      status: 'Ready',
      instructions: 'Reduce right and left sleeves by 0.5 inches without disturbing bullion cuff border.',
      createdDate: '2026-08-16',
      completedDate: '2026-08-25',
    },
    {
      id: 'alt-002',
      bookingId: 'bk-003',
      bookingNumber: 'BK-2026-0803',
      customerId: 'cust-005',
      customerName: 'Kavita Singhal',
      customerPhone: '+91 94140 88991',
      productId: 'prod-002',
      productName: 'Noor-e-Kashmir Ruby Velvet Bridal Lehenga',
      physicalItemId: 'LH003',
      size: 'L',
      alterationType: 'Blouse Margin Open',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      tailorName: 'Rameshbhai Darji',
      dueDate: '2026-08-29',
      status: 'In Progress',
      instructions: 'Release side seam allowance by 1.2 inches for comfortable chest fit.',
      createdDate: '2026-08-24',
    },
    {
      id: 'alt-003',
      bookingId: 'bk-006',
      bookingNumber: 'BK-2026-0806',
      customerId: 'cust-008',
      customerName: 'Arjun Kapoor',
      customerPhone: '+91 98100 44321',
      productId: 'prod-010',
      productName: 'Ivory & Rose Gold Raw Silk Achkan',
      physicalItemId: 'SH005',
      size: '40',
      alterationType: 'Chest & Waist Tapering',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      tailorName: 'Rameshbhai Darji',
      dueDate: '2026-09-02',
      status: 'Pending',
      instructions: 'Taper chest by 0.75 inches for slim-fit silhouette.',
      createdDate: '2026-08-23',
    },
    {
      id: 'alt-004',
      bookingId: 'bk-prev-02',
      bookingNumber: 'BK-2026-0795',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      productId: 'prod-005',
      productName: 'Marigold Mustard Mirror Kurta',
      physicalItemId: 'KJ002',
      size: '42',
      alterationType: 'Loose Mirror Stitching',
      assignedTailorId: 'stf-005',
      assignedTailorName: 'Suresh Master (Embroidery Specialist)',
      tailorName: 'Suresh Master',
      dueDate: '2026-08-29',
      status: 'In Progress',
      instructions: 'Re-anchor loose chest mirrors with silver zari thread.',
      createdDate: '2026-08-22',
    },
    {
      id: 'alt-005',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram Rathore',
      productId: 'prod-003',
      productName: 'Pastel Blush Peach Indo-Western',
      physicalItemId: 'IW002',
      size: '42',
      alterationType: 'Trousers Hemming',
      assignedTailorId: 'stf-003',
      assignedTailorName: 'Rameshbhai Darji (Master Tailor)',
      tailorName: 'Rameshbhai Darji',
      dueDate: '2026-08-27',
      status: 'Completed',
      instructions: 'Cowl trousers hem adjusted for 41 inch outseam.',
      createdDate: '2026-08-16',
      completedDate: '2026-08-24',
    },
  ];

  returns: ReturnRecord[] = [
    {
      id: 'ret-001',
      bookingId: 'bk-prev-01',
      bookingNumber: 'BK-2026-0790',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      returnDate: '2026-08-20',
      scheduledReturnDate: '2026-08-18',
      isLate: true,
      lateDays: 2,
      lateFeePerDay: 500,
      totalLateFee: 1000,
      inspectedItems: [
        {
          physicalItemId: 'KJ002',
          productId: 'prod-005',
          productName: 'Marigold Mustard Mirror-Work Kurta',
          size: '42',
          condition: 'Minor Damage',
          damageType: 'Loose Mirror Embroidery',
          damageDescription: 'Two small glass mirrors came off at front right panel.',
          damageRepairCost: 350,
          customerDeduction: 350,
          cleaningRequired: true,
          repairRequired: true,
        },
      ],
      totalDamageCost: 350,
      totalCustomerDeduction: 1350,
      securityDepositHeld: 4000,
      netDepositRefund: 2650,
      netCustomerPayable: 0,
      processedBy: 'Manojbhai Patel (Store Manager)',
      status: 'Completed',
      notes: 'Customer accepted deduction without dispute. Refund processed via UPI.',
      createdDate: '2026-08-20',
    },
    {
      id: 'ret-002',
      bookingId: 'bk-prev-03',
      bookingNumber: 'BK-2026-0785',
      customerId: 'cust-004',
      customerName: 'Rohan & Simran Mehta',
      returnDate: '2026-08-15',
      scheduledReturnDate: '2026-08-15',
      isLate: false,
      lateDays: 0,
      lateFeePerDay: 500,
      totalLateFee: 0,
      inspectedItems: [
        {
          physicalItemId: 'LH004',
          productId: 'prod-004',
          productName: 'Firozi & Mint Green Floral Chikankari Lehenga',
          size: 'M',
          condition: 'Excellent',
          cleaningRequired: true,
          repairRequired: false,
        },
      ],
      totalDamageCost: 0,
      totalCustomerDeduction: 0,
      securityDepositHeld: 8000,
      netDepositRefund: 8000,
      netCustomerPayable: 0,
      processedBy: 'Manojbhai Patel (Store Manager)',
      status: 'Completed',
      notes: 'Returned in pristine luxury condition. 100% deposit released instantly.',
      createdDate: '2026-08-15',
    },
    {
      id: 'ret-003',
      bookingId: 'bk-prev-04',
      bookingNumber: 'BK-2026-0780',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      returnDate: '2026-08-08',
      scheduledReturnDate: '2026-08-07',
      isLate: true,
      lateDays: 1,
      lateFeePerDay: 500,
      totalLateFee: 500,
      inspectedItems: [
        {
          physicalItemId: 'BG001',
          productId: 'prod-006',
          productName: 'Midnight Blue Italian Silk Bandhgala',
          size: '40',
          condition: 'Excellent',
          cleaningRequired: true,
          repairRequired: false,
        },
      ],
      totalDamageCost: 0,
      totalCustomerDeduction: 500,
      securityDepositHeld: 7000,
      netDepositRefund: 6500,
      netCustomerPayable: 0,
      processedBy: 'Pooja Shah (Showroom Lead)',
      status: 'Completed',
      notes: '1 day late return fee deducted. Net ₹6,500 refunded to UPI.',
      createdDate: '2026-08-08',
    },
  ];

  salesOrders: SalesOrder[] = [
    {
      id: 'so-001',
      orderNumber: 'SO-2026-0041',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      customerPhone: '+91 99099 88123',
      items: [
        {
          productId: 'prod-007',
          productName: 'Royal Maharaja Groom Accessories Hamper',
          sku: 'ACC-GROOM-007',
          size: 'Standard',
          price: 22000,
          quantity: 1,
          total: 22000,
        },
      ],
      subtotal: 22000,
      discount: 1000,
      taxRate: 5,
      taxAmount: 1050,
      finalTotal: 22050,
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      deliveryStatus: 'Delivered',
      createdDate: '2026-08-18',
      notes: 'Immediate handover at showroom billing counter.',
    },
    {
      id: 'so-002',
      orderNumber: 'SO-2026-0042',
      customerId: 'cust-005',
      customerName: 'Kavita & Aditya Singhal',
      customerPhone: '+91 94140 88991',
      items: [
        {
          productId: 'prod-015',
          productName: 'Heritage Rajputana Jadau Pearl Kalgi & Mala Set',
          sku: 'ACC-JADAU-015',
          size: 'Standard',
          price: 16500,
          quantity: 1,
          total: 16500,
        },
      ],
      subtotal: 16500,
      discount: 500,
      taxRate: 5,
      taxAmount: 800,
      finalTotal: 16800,
      paymentMethod: 'Credit Card',
      paymentStatus: 'Paid',
      deliveryStatus: 'Delivered',
      createdDate: '2026-08-21',
      notes: 'Purchased for groom brother wedding styling.',
    },
    {
      id: 'so-003',
      orderNumber: 'SO-2026-0043',
      customerId: 'cust-001',
      customerName: 'Vikram Rathore',
      customerPhone: '+91 98250 14892',
      items: [
        {
          productId: 'prod-017',
          productName: 'Pre-Tied Brocade Silk Royal Safa with Kalgi Mount',
          sku: 'ACC-SAFA-017',
          size: 'Adjustable',
          price: 8500,
          quantity: 1,
          total: 8500,
        },
      ],
      subtotal: 8500,
      discount: 0,
      taxRate: 5,
      taxAmount: 425,
      finalTotal: 8925,
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      deliveryStatus: 'Delivered',
      createdDate: '2026-08-24',
      notes: 'Packaged in royal velvet safa storage case.',
    },
  ];

  payments: PaymentRecord[] = [
    {
      id: 'pay-001',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      amount: 5000,
      paymentType: 'Advance',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/3891029192/HDFC',
      invoiceNumber: 'INV-2026-0801',
      date: '2026-08-15',
      notes: 'Advance booking token',
      receivedBy: 'Pooja Shah (Cashier)',
    },
    {
      id: 'pay-002',
      bookingId: 'bk-001',
      bookingNumber: 'BK-2026-0801',
      customerId: 'cust-001',
      customerName: 'Vikram & Ananya Rathore',
      amount: 16000,
      paymentType: 'Deposit',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/3891048821/HDFC',
      invoiceNumber: 'DEP-2026-0801',
      date: '2026-08-15',
      notes: 'Full security deposit received into escrow ledger',
      receivedBy: 'Pooja Shah (Cashier)',
    },
    {
      id: 'pay-003',
      bookingId: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      amount: 9450,
      paymentType: 'Final Payment',
      paymentMethod: 'Credit Card',
      transactionReference: 'POS/ICICI/882190',
      invoiceNumber: 'INV-2026-0802',
      date: '2026-08-24',
      notes: 'Full rental cleared before outfit handover',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-004',
      bookingId: 'bk-002',
      bookingNumber: 'BK-2026-0802',
      customerId: 'cust-002',
      customerName: 'Devangi & Hardik Joshi',
      amount: 15000,
      paymentType: 'Deposit',
      paymentMethod: 'Cash',
      invoiceNumber: 'DEP-2026-0802',
      date: '2026-08-24',
      notes: 'Cash security deposit held in store safe',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-005',
      bookingId: 'bk-003',
      bookingNumber: 'BK-2026-0803',
      customerId: 'cust-005',
      customerName: 'Kavita & Aditya Singhal',
      amount: 5000,
      paymentType: 'Advance',
      paymentMethod: 'Bank Transfer',
      transactionReference: 'NEFT/HDFC22910492',
      invoiceNumber: 'INV-2026-0803',
      date: '2026-08-20',
      notes: 'Advance token payment',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-006',
      bookingId: 'bk-003',
      bookingNumber: 'BK-2026-0803',
      customerId: 'cust-005',
      customerName: 'Kavita & Aditya Singhal',
      amount: 15000,
      paymentType: 'Deposit',
      paymentMethod: 'Bank Transfer',
      transactionReference: 'NEFT/HDFC22910493',
      invoiceNumber: 'DEP-2026-0803',
      date: '2026-08-20',
      notes: 'Security deposit held in escrow account',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-007',
      bookingId: 'bk-004',
      bookingNumber: 'BK-2026-0804',
      customerId: 'cust-006',
      customerName: 'Pranav & Tanvi Shah (NRI UK)',
      amount: 7560,
      paymentType: 'Final Payment',
      paymentMethod: 'Credit Card',
      transactionReference: 'POS/AMEX/778190',
      invoiceNumber: 'INV-2026-0804',
      date: '2026-08-25',
      notes: 'International Amex card settlement',
      receivedBy: 'Pooja Shah',
    },
    {
      id: 'pay-008',
      bookingId: 'bk-004',
      bookingNumber: 'BK-2026-0804',
      customerId: 'cust-006',
      customerName: 'Pranav & Tanvi Shah (NRI UK)',
      amount: 12000,
      paymentType: 'Deposit',
      paymentMethod: 'Credit Card',
      transactionReference: 'AUTH/AMEX/99012',
      invoiceNumber: 'DEP-2026-0804',
      date: '2026-08-25',
      notes: 'Card pre-auth deposit held',
      receivedBy: 'Pooja Shah',
    },
    {
      id: 'pay-009',
      bookingId: 'bk-prev-01',
      bookingNumber: 'BK-2026-0790',
      customerId: 'cust-003',
      customerName: 'Chirag Singhania',
      amount: 2650,
      paymentType: 'Deposit Refund',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/REF/99018239',
      invoiceNumber: 'REF-2026-0790',
      date: '2026-08-20',
      notes: 'Escrow deposit refund after deductions',
      receivedBy: 'Manojbhai Patel',
    },
    {
      id: 'pay-010',
      bookingId: 'bk-prev-03',
      bookingNumber: 'BK-2026-0785',
      customerId: 'cust-004',
      customerName: 'Rohan & Simran Mehta',
      amount: 8000,
      paymentType: 'Deposit Refund',
      paymentMethod: 'UPI',
      transactionReference: 'UPI/REF/88219012',
      invoiceNumber: 'REF-2026-0785',
      date: '2026-08-15',
      notes: 'Full deposit refund upon pristine return',
      receivedBy: 'Manojbhai Patel',
    },
  ];

  expenses: Expense[] = [
    {
      id: 'exp-001',
      category: 'Cleaning',
      title: 'Monthly Heavy Silk Drycleaning & Ozone Sanitization',
      amount: 12500,
      date: '2026-08-22',
      paidTo: 'Sparkle Luxury Garment Cleaners',
      paymentMethod: 'UPI',
      associatedType: 'Business',
      notes: 'Batch of 18 wedding outfits cleaned and packed with acid-free tissue paper.',
    },
    {
      id: 'exp-002',
      category: 'Tailoring',
      title: 'Master Tailor Fortnightly Piece-Rate Alteration Payout',
      amount: 16800,
      date: '2026-08-20',
      paidTo: 'Ramesh Master & Team',
      paymentMethod: 'Bank Transfer',
      associatedType: 'Business',
      notes: 'Alteration on 24 wedding pieces completed on schedule.',
    },
    {
      id: 'exp-003',
      category: 'Rent',
      title: 'Showroom Lease - Judges Bungalow Road Flagship',
      amount: 85000,
      date: '2026-08-01',
      paidTo: 'Shivalik Properties Ltd',
      paymentMethod: 'Bank Transfer',
      associatedType: 'Business',
    },
    {
      id: 'exp-004',
      category: 'Packaging',
      title: 'Branded Luxury Velvet Garment Bags & Wooden Hangers',
      amount: 9400,
      date: '2026-08-10',
      paidTo: 'Royal Craft Box & Packaging Surat',
      paymentMethod: 'UPI',
      associatedType: 'Business',
    },
    {
      id: 'exp-005',
      category: 'Maintenance',
      title: 'Industrial Steam Press Service & Boiler Maintenance',
      amount: 4200,
      date: '2026-08-14',
      paidTo: 'Siddhi Steam Systems Ahmedabad',
      paymentMethod: 'UPI',
      associatedType: 'Business',
    },
    {
      id: 'exp-006',
      category: 'Cleaning',
      title: 'Emergency Delicate Zari Stain Treatment & Spot Clean',
      amount: 3800,
      date: '2026-08-19',
      paidTo: 'Sparkle Luxury Garment Cleaners',
      paymentMethod: 'UPI',
      associatedType: 'Business',
    },
    {
      id: 'exp-007',
      category: 'Tailoring',
      title: 'Embroidery Gold Bullion Wire & Raw Material Purchase',
      amount: 6500,
      date: '2026-08-23',
      paidTo: 'Royal Zari Ghar Jaipur',
      paymentMethod: 'UPI',
      associatedType: 'Business',
    },
  ];

  suppliers: Supplier[] = [
    {
      id: 'sup-001',
      name: 'Royal Heritage Weaves Jaipur',
      contactPerson: 'Harishankar Sharma',
      phone: '+91 94140 33890',
      email: 'orders@royalheritageweaves.in',
      address: 'Johari Bazaar, Near Hawa Mahal',
      city: 'Jaipur',
      categoriesProvided: ['Sherwani', 'Bandhgala', 'Indo-Western'],
      gstNumber: '08AAACR8821N1Z5',
      totalSupplied: 480000,
      pendingBalance: 25000,
      notes: 'Specialist in pure silk bullion and hand zardozi work.',
    },
    {
      id: 'sup-002',
      name: 'Vrindavan Zari & Bridal Emporium',
      contactPerson: 'Sunilbhai Vora',
      phone: '+91 98241 66720',
      email: 'vrindavan.zari@gmail.com',
      address: 'Ring Road Textile Market',
      city: 'Surat',
      categoriesProvided: ['Bridal Lehenga', 'Designer Saree', 'Dupattas'],
      gstNumber: '24AABPV1928K1ZZ',
      totalSupplied: 890000,
      pendingBalance: 40000,
      notes: 'Top tier bridal lehenga fabrics with high cancan support.',
    },
    {
      id: 'sup-003',
      name: 'Shahi Pagdi & Accessories Delhi',
      contactPerson: 'Gurmeet Singh',
      phone: '+91 98110 55432',
      email: 'gurmeet@shahipagdi.com',
      address: 'Chandni Chowk Market',
      city: 'New Delhi',
      categoriesProvided: ['Safa & Pagdi', 'Kalgi & Brooch', 'Mojaris'],
      gstNumber: '07AAACS1120M1ZK',
      totalSupplied: 140000,
      pendingBalance: 0,
      notes: 'Pre-tied luxury safas with velvet trims.',
    },
    {
      id: 'sup-004',
      name: 'Varanasi Master Handlooms',
      contactPerson: 'Ramnarayan Mishra',
      phone: '+91 94520 11984',
      email: 'mishra.varanasi@handloom.in',
      address: 'Chowk Varanasi, Near Kashi Vishwanath',
      city: 'Varanasi',
      categoriesProvided: ['Banarasi Silk Saree', 'Katan Silk Brocades'],
      gstNumber: '09AAABM2231K1ZM',
      totalSupplied: 320000,
      pendingBalance: 12000,
      notes: 'Pure silver & gold zari weaving cooperative.',
    },
    {
      id: 'sup-005',
      name: 'Royal Craft Box & Packaging Surat',
      contactPerson: 'Dhavalbhai Doshi',
      phone: '+91 98251 44550',
      email: 'sales@royalcraftbox.com',
      address: 'GIDC Khatodara',
      city: 'Surat',
      categoriesProvided: ['Garment Bags', 'Velvet Boxes', 'Hangers'],
      gstNumber: '24AADFD8892L1Z3',
      totalSupplied: 75000,
      pendingBalance: 0,
      notes: 'Custom embroidered boutique packaging.',
    },
  ];

  staff: StaffMember[] = [
    {
      id: 'stf-001',
      name: 'Manojbhai Patel',
      role: 'Manager',
      phone: '+91 98251 00223',
      email: 'manoj.patel@vastraveda.in',
      salary: 45000,
      joiningDate: '2024-01-15',
      active: true,
      tasksAssigned: 12,
      specialization: 'Showroom Operations & Return Inspections',
      permissions: ['Full Access', 'Billing', 'Deposit Approvals', 'Inventory Relocation'],
    },
    {
      id: 'stf-002',
      name: 'Pooja Shah',
      role: 'Sales Staff',
      phone: '+91 97230 44512',
      email: 'pooja.shah@vastraveda.in',
      salary: 28000,
      joiningDate: '2024-06-01',
      active: true,
      tasksAssigned: 8,
      specialization: 'Bridal Consultation & Luxury Styling',
      permissions: ['Customer Registration', 'Rental Booking Creation', 'WhatsApp Invoices'],
    },
    {
      id: 'stf-003',
      name: 'Rameshbhai Darji',
      role: 'Tailor',
      phone: '+91 94280 11928',
      email: 'ramesh.tailor@vastraveda.in',
      salary: 35000,
      joiningDate: '2024-02-10',
      active: true,
      tasksAssigned: 4,
      specialization: 'Master Sherwani & Bridal Blouse Cut',
      permissions: ['Alteration Board', 'Measurements Update'],
    },
    {
      id: 'stf-004',
      name: 'Ketan Vaghela',
      role: 'Inventory Staff',
      phone: '+91 96010 33451',
      email: 'ketan.v@vastraveda.in',
      salary: 24000,
      joiningDate: '2025-01-05',
      active: true,
      tasksAssigned: 6,
      specialization: 'QR Tagging, Dryclean Handover & Quality Inspection',
      permissions: ['Inventory Status Mover', 'Cleaning Handover', 'QR Generator'],
    },
    {
      id: 'stf-005',
      name: 'Suresh Darji',
      role: 'Tailor',
      phone: '+91 98980 66551',
      email: 'suresh.darji@vastraveda.in',
      salary: 26000,
      joiningDate: '2025-03-01',
      active: true,
      tasksAssigned: 2,
      specialization: 'Mirror & Zari Repair Specialist',
      permissions: ['Alteration Board'],
    },
    {
      id: 'stf-006',
      name: 'Neha Joshi',
      role: 'Accountant',
      phone: '+91 98240 99882',
      email: 'neha.joshi@vastraveda.in',
      salary: 32000,
      joiningDate: '2025-02-15',
      active: true,
      tasksAssigned: 3,
      specialization: 'GST Invoicing, Escrow Ledger & UPI Reconciliation',
      permissions: ['Financial Reports', 'Expenses', 'Payments Ledger'],
    },
  ];

  settings: StoreSettings = {
    businessName: 'VastraVeda Bridal & Groom Couture',
    storeName: 'VastraVeda Atelier & Rental Studio',
    tagline: 'India’s Premier Wedding Wear Rental & Bespoke Studio',
    gstin: '24AAFCV9821L1Z4',
    address: 'Showroom 101-104, Shivalik Highstreet, Judges Bungalow Road, Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    phone: '+91 79 4890 2200',
    whatsapp: '+91 98250 14892',
    email: 'contact@vastravedacouture.com',
    upiId: 'vastraveda@okhdfcbank',
    currencySymbol: '₹',
    defaultTaxRate: 5,
    defaultDepositRate: 50,
    defaultSecurityDepositPercent: 50,
    lateFeePerDay: 500,
    cleaningBufferDays: 1,
    alterationBufferDays: 2,
    termsAndConditions:
      '1. Security deposit is fully refundable subject to item condition on return inspection.\n2. Late returns attract ₹500/day per garment.\n3. Any fabric tear, wine/grease stains, or lost brooch accessories will be deducted from the security deposit at actual repair/replacement cost.\n4. Outfits must be returned on the scheduled return date before 8:00 PM.',
    language: 'en',
  };

  auditLogs: AuditLog[] = [
    {
      id: 'log-001',
      timestamp: '2026-08-26 09:30:15',
      user: 'Manojbhai Patel (Manager)',
      userName: 'Manojbhai Patel',
      action: 'Created Booking',
      target: 'BK-2026-0801',
      details: 'Booked 2 outfits for Vikram & Ananya Rathore wedding.',
    },
    {
      id: 'log-002',
      timestamp: '2026-08-26 10:14:02',
      user: 'Pooja Shah (Sales)',
      userName: 'Pooja Shah',
      action: 'Logged Advance Payment',
      target: 'BK-2026-0801',
      details: 'Recorded ₹5,000 Advance + ₹16,000 Security Deposit via UPI.',
    },
    {
      id: 'log-003',
      timestamp: '2026-08-25 16:45:00',
      user: 'Ramesh Darji (Tailor)',
      userName: 'Ramesh Darji',
      action: 'Completed Alteration',
      target: 'SH002 (Sleeve shortening)',
      details: 'Marked alteration task as Ready for trial.',
    },
    {
      id: 'log-004',
      timestamp: '2026-08-25 11:20:00',
      user: 'Pooja Shah (Sales)',
      userName: 'Pooja Shah',
      action: 'Dispatched Rental Handover',
      target: 'BK-2026-0804',
      details: 'Handed over Emerald Green Sangeet Lehenga to Tanvi Shah.',
    },
    {
      id: 'log-005',
      timestamp: '2026-08-24 14:10:30',
      user: 'Manojbhai Patel (Manager)',
      userName: 'Manojbhai Patel',
      action: 'Created Sales Order',
      target: 'SO-2026-0043',
      details: 'Sold Royal Brocade Safa to Vikram Rathore (₹8,925).',
    },
    {
      id: 'log-006',
      timestamp: '2026-08-20 18:30:10',
      user: 'Manojbhai Patel (Manager)',
      userName: 'Manojbhai Patel',
      action: 'Processed Return',
      target: 'BK-2026-0790',
      details: 'Inspected Haldi Kurta KJ002. Deducted ₹1,000 late fee and ₹350 mirror repair. Refunded ₹2,650 via UPI.',
    },
  ];

  // Helper method: Check date overlap for a physical item
  isItemAvailableForDates(
    physicalItemId: string,
    startDateStr: string,
    endDateStr: string,
    excludeBookingId?: string
  ): { available: boolean; conflictingBooking?: Booking; reason?: string } {
    const item = this.inventoryItems.find((i) => i.id === physicalItemId);
    if (!item) {
      return { available: false, reason: 'Physical item not found' };
    }

    if (item.status === 'Sold' || item.status === 'Lost' || item.status === 'Damaged' || item.status === 'Inactive') {
      return { available: false, reason: `Item is currently marked as ${item.status}` };
    }

    const reqStart = new Date(startDateStr).getTime();
    const reqEnd = new Date(endDateStr || startDateStr).getTime();

    // Check active / confirmed bookings that include this physical item
    for (const booking of this.bookings) {
      if (excludeBookingId && booking.id === excludeBookingId) continue;
      if (booking.bookingStatus === 'Cancelled' || booking.bookingStatus === 'Completed') continue;

      const hasItem = booking.items.some((bi) => bi.physicalItemId === physicalItemId);
      if (!hasItem) continue;

      // Calculate buffer dates (add cleaning buffer days)
      const bStart = new Date(booking.rentalStartDate).getTime();
      const bEnd = new Date(booking.rentalEndDate || booking.returnDate).getTime() + (this.settings.cleaningBufferDays || 1) * 86400000;

      // Overlap condition: reqStart <= bEnd && reqEnd >= bStart
      if (reqStart <= bEnd && reqEnd >= bStart) {
        return {
          available: false,
          conflictingBooking: booking,
          reason: `Booked for ${booking.customerName} (${booking.rentalStartDate} to ${booking.returnDate})`,
        };
      }
    }

    return { available: true };
  }
}

export const db = new Store();
